// ─────────────────────────────────────────────────────────────────────────────
// Home survey catalog — the data backbone of the index-page survey pipeline.
//
// The landing page walks visitors through four phases:
//   1. pick a country on the spinning globe,
//   2. pick POIs from a media wall,
//   3. watch the AI agent reason an itinerary together,
//   4. explore the finished plan on an animated map.
//
// This module is client-safe (no server imports): both the React scenes and
// the /api/home/* routes import the same catalog so the server never trusts
// client-provided POI payloads — only ids that must resolve here.
// ─────────────────────────────────────────────────────────────────────────────

export type HomeCountryCode = "jp" | "tw" | "us";
export type HomeMediaKind = "photo" | "video" | "insta";
export type HomePoiType = "activity" | "restaurant";

export interface HomeCountry {
  code: HomeCountryCode;
  name: string;
  nameZh: string;
  flag: string;
  /** Marker anchor on the globe. */
  lat: number;
  lng: number;
  tagline: string;
  taglineZh: string;
  currency: { code: string; symbol: string; perUsd: number; round: number };
}

export interface HomePoi {
  id: string;
  country: HomeCountryCode;
  name: string;
  nameZh: string;
  city: string;
  itemType: HomePoiType;
  lat: number;
  lng: number;
  blurb: string;
  blurbZh: string;
  media: HomeMediaKind;
  /** Free-text query the photo proxy uses to find a representative image. */
  photoQuery: string;
  /** Typical per-person spend in USD (entry / meal), used for cost estimates. */
  costUsd: number;
  /** Typical visit length in minutes, used by the fallback scheduler. */
  stayMinutes: number;
  /** Hue (0-360) seeding the gradient placeholder when no photo is available. */
  hue: number;
  emoji: string;
  /** Faux social handle for the Instagram-styled cards. */
  handle: string;
  likes: number;
  /** Pseudo runtime for video-styled cards, seconds. */
  videoSeconds?: number;
}

export const HOME_COUNTRIES: HomeCountry[] = [
  {
    code: "jp",
    name: "Japan",
    nameZh: "日本",
    flag: "🇯🇵",
    lat: 36.2,
    lng: 138.25,
    tagline: "Neon crossings, quiet shrines",
    taglineZh: "霓虹路口與寧靜神社",
    currency: { code: "JPY", symbol: "¥", perUsd: 155, round: 100 },
  },
  {
    code: "tw",
    name: "Taiwan",
    nameZh: "台灣",
    flag: "🇹🇼",
    lat: 23.7,
    lng: 121.0,
    tagline: "Night markets, misty mountains",
    taglineZh: "夜市與山嵐",
    currency: { code: "TWD", symbol: "NT$", perUsd: 32, round: 10 },
  },
  {
    code: "us",
    name: "United States",
    nameZh: "美國",
    flag: "🇺🇸",
    lat: 39.8,
    lng: -98.6,
    tagline: "Skylines, coasts, canyons",
    taglineZh: "天際線、海岸與峽谷",
    currency: { code: "USD", symbol: "$", perUsd: 1, round: 1 },
  },
];

export const HOME_POIS: HomePoi[] = [
  // ── Japan ──────────────────────────────────────────────────────────────────
  {
    id: "jp-shibuya-crossing",
    country: "jp",
    name: "Shibuya Crossing",
    nameZh: "澀谷十字路口",
    city: "Tokyo",
    itemType: "activity",
    lat: 35.6595,
    lng: 139.7005,
    blurb: "The world's busiest scramble — best at dusk from above.",
    blurbZh: "全球最繁忙的十字路口，黃昏時從高處俯瞰最美。",
    media: "video",
    photoQuery: "Shibuya Crossing Tokyo",
    costUsd: 0,
    stayMinutes: 45,
    hue: 210,
    emoji: "🚦",
    handle: "tokyo.nights",
    likes: 48213,
    videoSeconds: 34,
  },
  {
    id: "jp-sensoji",
    country: "jp",
    name: "Sensō-ji Temple",
    nameZh: "淺草寺",
    city: "Tokyo",
    itemType: "activity",
    lat: 35.7148,
    lng: 139.7967,
    blurb: "Tokyo's oldest temple behind the Thunder Gate lantern.",
    blurbZh: "穿過雷門大燈籠，造訪東京最古老的寺院。",
    media: "photo",
    photoQuery: "Sensoji Temple Asakusa Tokyo",
    costUsd: 0,
    stayMinutes: 75,
    hue: 0,
    emoji: "⛩️",
    handle: "asakusa.walks",
    likes: 21870,
  },
  {
    id: "jp-teamlab",
    country: "jp",
    name: "teamLab Planets",
    nameZh: "teamLab Planets",
    city: "Tokyo",
    itemType: "activity",
    lat: 35.6494,
    lng: 139.7898,
    blurb: "Barefoot, knee-deep digital art you walk through.",
    blurbZh: "赤腳走進水中的沉浸式數位藝術。",
    media: "insta",
    photoQuery: "teamLab Planets Tokyo",
    costUsd: 25,
    stayMinutes: 120,
    hue: 280,
    emoji: "✨",
    handle: "teamlab.fan",
    likes: 90412,
  },
  {
    id: "jp-tsukiji",
    country: "jp",
    name: "Tsukiji Outer Market",
    nameZh: "築地場外市場",
    city: "Tokyo",
    itemType: "restaurant",
    lat: 35.6654,
    lng: 139.7707,
    blurb: "Tamago skewers, uni bowls and knife shops at dawn.",
    blurbZh: "清晨的玉子燒、海膽丼與職人刀具街。",
    media: "photo",
    photoQuery: "Tsukiji Outer Market Tokyo food",
    costUsd: 18,
    stayMinutes: 75,
    hue: 30,
    emoji: "🍣",
    handle: "tsukiji.eats",
    likes: 33780,
  },
  {
    id: "jp-meiji",
    country: "jp",
    name: "Meiji Shrine",
    nameZh: "明治神宮",
    city: "Tokyo",
    itemType: "activity",
    lat: 35.6764,
    lng: 139.6993,
    blurb: "A forest of 100,000 trees hiding a serene shrine.",
    blurbZh: "十萬棵樹的森林裡，藏著一座寧靜神宮。",
    media: "photo",
    photoQuery: "Meiji Shrine Tokyo torii",
    costUsd: 0,
    stayMinutes: 75,
    hue: 130,
    emoji: "🌳",
    handle: "shrine.paths",
    likes: 15204,
  },
  {
    id: "jp-skytree",
    country: "jp",
    name: "Tokyo Skytree",
    nameZh: "東京晴空塔",
    city: "Tokyo",
    itemType: "activity",
    lat: 35.7101,
    lng: 139.8107,
    blurb: "634 m of glass-floor views over the Kanto plain.",
    blurbZh: "634 公尺高空玻璃地板，俯瞰整個關東平原。",
    media: "video",
    photoQuery: "Tokyo Skytree observation deck",
    costUsd: 20,
    stayMinutes: 90,
    hue: 195,
    emoji: "🗼",
    handle: "sky.tokyo",
    likes: 27490,
    videoSeconds: 51,
  },
  {
    id: "jp-ichiran",
    country: "jp",
    name: "Ichiran Ramen Shibuya",
    nameZh: "一蘭拉麵 澀谷店",
    city: "Tokyo",
    itemType: "restaurant",
    lat: 35.659,
    lng: 139.7006,
    blurb: "Solo-booth tonkotsu ramen, ordered by paper slip.",
    blurbZh: "一人一格的豚骨拉麵，用紙單客製你的那一碗。",
    media: "insta",
    photoQuery: "Ichiran Ramen Shibuya",
    costUsd: 12,
    stayMinutes: 60,
    hue: 18,
    emoji: "🍜",
    handle: "ramen.diaries",
    likes: 64118,
  },
  {
    id: "jp-goldengai",
    country: "jp",
    name: "Shinjuku Golden Gai",
    nameZh: "新宿黃金街",
    city: "Tokyo",
    itemType: "activity",
    lat: 35.6938,
    lng: 139.7034,
    blurb: "Two hundred tiny bars in six lantern-lit alleys.",
    blurbZh: "六條燈籠小巷裡，擠著兩百間迷你酒吧。",
    media: "photo",
    photoQuery: "Shinjuku Golden Gai alley night",
    costUsd: 15,
    stayMinutes: 90,
    hue: 45,
    emoji: "🏮",
    handle: "golden.gai",
    likes: 41866,
  },
  {
    id: "jp-fushimi",
    country: "jp",
    name: "Fushimi Inari Taisha",
    nameZh: "伏見稻荷大社",
    city: "Kyoto",
    itemType: "activity",
    lat: 34.9671,
    lng: 135.7727,
    blurb: "Ten thousand vermilion torii winding up the mountain.",
    blurbZh: "萬座朱紅鳥居，蜿蜒而上整座稻荷山。",
    media: "insta",
    photoQuery: "Fushimi Inari Shrine torii gates Kyoto",
    costUsd: 0,
    stayMinutes: 120,
    hue: 12,
    emoji: "🦊",
    handle: "kyoto.gates",
    likes: 118530,
  },
  {
    id: "jp-kinkakuji",
    country: "jp",
    name: "Kinkaku-ji",
    nameZh: "金閣寺",
    city: "Kyoto",
    itemType: "activity",
    lat: 35.0394,
    lng: 135.7292,
    blurb: "The Golden Pavilion mirrored in its still pond.",
    blurbZh: "金色樓閣倒映在鏡湖池上。",
    media: "photo",
    photoQuery: "Kinkakuji Golden Pavilion Kyoto",
    costUsd: 4,
    stayMinutes: 75,
    hue: 50,
    emoji: "🏯",
    handle: "zen.kyoto",
    likes: 52904,
  },
  {
    id: "jp-arashiyama",
    country: "jp",
    name: "Arashiyama Bamboo Grove",
    nameZh: "嵐山竹林小徑",
    city: "Kyoto",
    itemType: "activity",
    lat: 35.017,
    lng: 135.671,
    blurb: "Green light filtering through a swaying bamboo canyon.",
    blurbZh: "搖曳竹海間灑落的綠色光影。",
    media: "video",
    photoQuery: "Arashiyama Bamboo Grove Kyoto",
    costUsd: 0,
    stayMinutes: 60,
    hue: 110,
    emoji: "🎋",
    handle: "bamboo.path",
    likes: 38217,
    videoSeconds: 28,
  },
  {
    id: "jp-dotonbori",
    country: "jp",
    name: "Dōtonbori",
    nameZh: "道頓堀",
    city: "Osaka",
    itemType: "restaurant",
    lat: 34.6687,
    lng: 135.5013,
    blurb: "Takoyaki, kushikatsu and the Glico runner's neon canal.",
    blurbZh: "章魚燒、串炸與固力果跑者霓虹河岸。",
    media: "video",
    photoQuery: "Dotonbori Osaka neon canal",
    costUsd: 16,
    stayMinutes: 90,
    hue: 330,
    emoji: "🐙",
    handle: "osaka.bites",
    likes: 73344,
    videoSeconds: 42,
  },
  // ── Taiwan ─────────────────────────────────────────────────────────────────
  {
    id: "tw-taipei101",
    country: "tw",
    name: "Taipei 101",
    nameZh: "台北 101",
    city: "Taipei",
    itemType: "activity",
    lat: 25.034,
    lng: 121.5645,
    blurb: "Bamboo-shaped supertall with an 89th-floor lookout.",
    blurbZh: "竹節造型摩天樓，89 樓觀景台看盡台北。",
    media: "photo",
    photoQuery: "Taipei 101 tower",
    costUsd: 20,
    stayMinutes: 90,
    hue: 200,
    emoji: "🏙️",
    handle: "taipei.sky",
    likes: 45112,
  },
  {
    id: "tw-jiufen",
    country: "tw",
    name: "Jiufen Old Street",
    nameZh: "九份老街",
    city: "New Taipei",
    itemType: "activity",
    lat: 25.1097,
    lng: 121.8444,
    blurb: "Lantern-lit teahouses stacked on a misty hillside.",
    blurbZh: "山城茶樓與紅燈籠，霧裡的懷舊老街。",
    media: "insta",
    photoQuery: "Jiufen Old Street lanterns teahouse",
    costUsd: 10,
    stayMinutes: 150,
    hue: 8,
    emoji: "🏮",
    handle: "jiufen.mist",
    likes: 98730,
  },
  {
    id: "tw-shilin",
    country: "tw",
    name: "Shilin Night Market",
    nameZh: "士林夜市",
    city: "Taipei",
    itemType: "restaurant",
    lat: 25.0881,
    lng: 121.524,
    blurb: "Fried chicken bigger than your face, stinky tofu dares.",
    blurbZh: "比臉大的雞排與臭豆腐挑戰，夜市經典全到位。",
    media: "video",
    photoQuery: "Shilin Night Market Taipei street food",
    costUsd: 12,
    stayMinutes: 120,
    hue: 35,
    emoji: "🍢",
    handle: "night.market.tw",
    likes: 61420,
    videoSeconds: 47,
  },
  {
    id: "tw-cks",
    country: "tw",
    name: "Chiang Kai-shek Memorial",
    nameZh: "中正紀念堂",
    city: "Taipei",
    itemType: "activity",
    lat: 25.0347,
    lng: 121.5217,
    blurb: "White marble hall, blue roof, hourly guard ceremony.",
    blurbZh: "白牆藍瓦的紀念堂，整點衛兵交接不容錯過。",
    media: "photo",
    photoQuery: "Chiang Kai-shek Memorial Hall Taipei",
    costUsd: 0,
    stayMinutes: 75,
    hue: 220,
    emoji: "🏛️",
    handle: "taipei.walks",
    likes: 18960,
  },
  {
    id: "tw-elephant",
    country: "tw",
    name: "Elephant Mountain Trail",
    nameZh: "象山步道",
    city: "Taipei",
    itemType: "activity",
    lat: 25.0235,
    lng: 121.5707,
    blurb: "Twenty sweaty minutes up to the classic 101 skyline shot.",
    blurbZh: "爬二十分鐘階梯，換一張經典 101 天際線。",
    media: "insta",
    photoQuery: "Elephant Mountain Taipei skyline viewpoint",
    costUsd: 0,
    stayMinutes: 90,
    hue: 150,
    emoji: "⛰️",
    handle: "hike.taipei",
    likes: 53308,
  },
  {
    id: "tw-dintaifung",
    country: "tw",
    name: "Din Tai Fung (Xinyi)",
    nameZh: "鼎泰豐 信義店",
    city: "Taipei",
    itemType: "restaurant",
    lat: 25.0333,
    lng: 121.5636,
    blurb: "Eighteen-fold xiao long bao from the original kitchen.",
    blurbZh: "十八摺小籠包，發源店的經典手藝。",
    media: "photo",
    photoQuery: "Din Tai Fung xiao long bao Taipei",
    costUsd: 22,
    stayMinutes: 75,
    hue: 40,
    emoji: "🥟",
    handle: "dumpling.club",
    likes: 70215,
  },
  {
    id: "tw-longshan",
    country: "tw",
    name: "Longshan Temple",
    nameZh: "龍山寺",
    city: "Taipei",
    itemType: "activity",
    lat: 25.0372,
    lng: 121.4999,
    blurb: "Incense spirals under dragon-carved eaves since 1738.",
    blurbZh: "1738 年至今，龍簷下香煙裊裊。",
    media: "photo",
    photoQuery: "Longshan Temple Taipei incense",
    costUsd: 0,
    stayMinutes: 60,
    hue: 350,
    emoji: "🐉",
    handle: "temple.tw",
    likes: 24871,
  },
  {
    id: "tw-beitou",
    country: "tw",
    name: "Beitou Hot Springs",
    nameZh: "北投溫泉",
    city: "Taipei",
    itemType: "activity",
    lat: 25.137,
    lng: 121.5065,
    blurb: "Steaming sulfur valley and Japanese-era bathhouses.",
    blurbZh: "硫磺谷蒸氣與日式溫泉浴場。",
    media: "video",
    photoQuery: "Beitou Thermal Valley hot spring Taipei",
    costUsd: 15,
    stayMinutes: 120,
    hue: 170,
    emoji: "♨️",
    handle: "onsen.tw",
    likes: 31094,
    videoSeconds: 39,
  },
  {
    id: "tw-ximending",
    country: "tw",
    name: "Ximending",
    nameZh: "西門町",
    city: "Taipei",
    itemType: "activity",
    lat: 25.0421,
    lng: 121.5071,
    blurb: "Taipei's Harajuku — street art, sneakers, bubble tea.",
    blurbZh: "台北的原宿——塗鴉、潮鞋與手搖飲。",
    media: "insta",
    photoQuery: "Ximending Taipei street",
    costUsd: 8,
    stayMinutes: 90,
    hue: 300,
    emoji: "🧋",
    handle: "ximen.vibes",
    likes: 44560,
  },
  {
    id: "tw-palace",
    country: "tw",
    name: "National Palace Museum",
    nameZh: "國立故宮博物院",
    city: "Taipei",
    itemType: "activity",
    lat: 25.1024,
    lng: 121.5485,
    blurb: "The jadeite cabbage and 700,000 imperial treasures.",
    blurbZh: "翠玉白菜與七十萬件皇家珍藏。",
    media: "photo",
    photoQuery: "National Palace Museum Taipei",
    costUsd: 11,
    stayMinutes: 150,
    hue: 95,
    emoji: "🥬",
    handle: "museum.tw",
    likes: 19233,
  },
  {
    id: "tw-yehliu",
    country: "tw",
    name: "Yehliu Geopark",
    nameZh: "野柳地質公園",
    city: "New Taipei",
    itemType: "activity",
    lat: 25.2061,
    lng: 121.6906,
    blurb: "The Queen's Head and a coastline of alien rock.",
    blurbZh: "女王頭與外星地貌的海岸線。",
    media: "video",
    photoQuery: "Yehliu Geopark Queen's Head rock",
    costUsd: 4,
    stayMinutes: 120,
    hue: 185,
    emoji: "🪨",
    handle: "geo.coast",
    likes: 28741,
    videoSeconds: 31,
  },
  {
    id: "tw-raohe",
    country: "tw",
    name: "Raohe Night Market",
    nameZh: "饒河街觀光夜市",
    city: "Taipei",
    itemType: "restaurant",
    lat: 25.0509,
    lng: 121.5775,
    blurb: "Pepper buns from a clay oven by a glowing temple gate.",
    blurbZh: "廟口炭爐胡椒餅，一條街吃到底。",
    media: "photo",
    photoQuery: "Raohe Street Night Market pepper bun Taipei",
    costUsd: 10,
    stayMinutes: 90,
    hue: 25,
    emoji: "🔥",
    handle: "raohe.eats",
    likes: 39482,
  },
  // ── United States ──────────────────────────────────────────────────────────
  {
    id: "us-timessquare",
    country: "us",
    name: "Times Square",
    nameZh: "時報廣場",
    city: "New York",
    itemType: "activity",
    lat: 40.758,
    lng: -73.9855,
    blurb: "A canyon of billboards that never dims.",
    blurbZh: "永不熄滅的廣告看板峽谷。",
    media: "video",
    photoQuery: "Times Square New York night",
    costUsd: 0,
    stayMinutes: 60,
    hue: 320,
    emoji: "🎭",
    handle: "nyc.lights",
    likes: 87320,
    videoSeconds: 36,
  },
  {
    id: "us-centralpark",
    country: "us",
    name: "Central Park",
    nameZh: "中央公園",
    city: "New York",
    itemType: "activity",
    lat: 40.7829,
    lng: -73.9654,
    blurb: "843 acres of lawns, lakes and skyline frames.",
    blurbZh: "843 英畝的草坪、湖泊與天際線取景框。",
    media: "photo",
    photoQuery: "Central Park New York aerial autumn",
    costUsd: 0,
    stayMinutes: 120,
    hue: 120,
    emoji: "🌳",
    handle: "park.nyc",
    likes: 51209,
  },
  {
    id: "us-brooklynbridge",
    country: "us",
    name: "Brooklyn Bridge",
    nameZh: "布魯克林大橋",
    city: "New York",
    itemType: "activity",
    lat: 40.7061,
    lng: -73.9969,
    blurb: "Walk the wooden promenade at golden hour.",
    blurbZh: "黃金時刻漫步木棧道，曼哈頓就在身後。",
    media: "insta",
    photoQuery: "Brooklyn Bridge walkway sunset",
    costUsd: 0,
    stayMinutes: 75,
    hue: 28,
    emoji: "🌉",
    handle: "bridge.walks",
    likes: 66104,
  },
  {
    id: "us-katz",
    country: "us",
    name: "Katz's Delicatessen",
    nameZh: "Katz's 熟食店",
    city: "New York",
    itemType: "restaurant",
    lat: 40.7223,
    lng: -73.9874,
    blurb: "Hand-carved pastrami on rye since 1888.",
    blurbZh: "1888 年至今的手切煙燻牛肉三明治。",
    media: "photo",
    photoQuery: "Katz's Delicatessen pastrami sandwich New York",
    costUsd: 28,
    stayMinutes: 60,
    hue: 15,
    emoji: "🥪",
    handle: "deli.legend",
    likes: 47883,
  },
  {
    id: "us-goldengate",
    country: "us",
    name: "Golden Gate Bridge",
    nameZh: "金門大橋",
    city: "San Francisco",
    itemType: "activity",
    lat: 37.8199,
    lng: -122.4783,
    blurb: "International-orange towers above the fog line.",
    blurbZh: "國際橘塔頂破霧而出。",
    media: "photo",
    photoQuery: "Golden Gate Bridge fog San Francisco",
    costUsd: 0,
    stayMinutes: 90,
    hue: 14,
    emoji: "🌁",
    handle: "fog.city",
    likes: 93412,
  },
  {
    id: "us-alcatraz",
    country: "us",
    name: "Alcatraz Island",
    nameZh: "惡魔島",
    city: "San Francisco",
    itemType: "activity",
    lat: 37.8267,
    lng: -122.423,
    blurb: "Ferry to the infamous island prison and its audio tour.",
    blurbZh: "搭渡輪登上惡名昭彰的監獄島。",
    media: "video",
    photoQuery: "Alcatraz Island prison San Francisco",
    costUsd: 45,
    stayMinutes: 180,
    hue: 205,
    emoji: "⛴️",
    handle: "alcatraz.tour",
    likes: 35671,
    videoSeconds: 58,
  },
  {
    id: "us-fishermanswharf",
    country: "us",
    name: "Fisherman's Wharf",
    nameZh: "漁人碼頭",
    city: "San Francisco",
    itemType: "restaurant",
    lat: 37.808,
    lng: -122.4177,
    blurb: "Clam chowder in sourdough, sea lions on Pier 39.",
    blurbZh: "酸麵包蛤蜊巧達湯，39 號碼頭看海獅。",
    media: "photo",
    photoQuery: "Fisherman's Wharf Pier 39 San Francisco",
    costUsd: 24,
    stayMinutes: 90,
    hue: 38,
    emoji: "🦭",
    handle: "wharf.eats",
    likes: 29904,
  },
  {
    id: "us-griffith",
    country: "us",
    name: "Griffith Observatory",
    nameZh: "葛瑞菲斯天文台",
    city: "Los Angeles",
    itemType: "activity",
    lat: 34.1184,
    lng: -118.3004,
    blurb: "Telescopes, the Hollywood sign and the LA basin aglow.",
    blurbZh: "望遠鏡、好萊塢標誌與洛杉磯夜景。",
    media: "insta",
    photoQuery: "Griffith Observatory Los Angeles sunset",
    costUsd: 0,
    stayMinutes: 105,
    hue: 260,
    emoji: "🔭",
    handle: "la.skies",
    likes: 72458,
  },
  {
    id: "us-santamonica",
    country: "us",
    name: "Santa Monica Pier",
    nameZh: "聖塔莫尼卡碼頭",
    city: "Los Angeles",
    itemType: "activity",
    lat: 34.0092,
    lng: -118.4973,
    blurb: "Ferris wheel over the Pacific at the end of Route 66.",
    blurbZh: "66 號公路終點，太平洋上的摩天輪。",
    media: "video",
    photoQuery: "Santa Monica Pier ferris wheel",
    costUsd: 10,
    stayMinutes: 120,
    hue: 190,
    emoji: "🎡",
    handle: "socal.coast",
    likes: 58112,
    videoSeconds: 44,
  },
  {
    id: "us-innout",
    country: "us",
    name: "In-N-Out Burger",
    nameZh: "In-N-Out 漢堡",
    city: "Los Angeles",
    itemType: "restaurant",
    lat: 34.0983,
    lng: -118.3268,
    blurb: "Animal-style fries off the not-so-secret menu.",
    blurbZh: "隱藏菜單 Animal Style 薯條，加州限定。",
    media: "photo",
    photoQuery: "In-N-Out Burger animal style California",
    costUsd: 9,
    stayMinutes: 45,
    hue: 5,
    emoji: "🍔",
    handle: "burger.runs",
    likes: 40217,
  },
  {
    id: "us-met",
    country: "us",
    name: "The Met Museum",
    nameZh: "大都會藝術博物館",
    city: "New York",
    itemType: "activity",
    lat: 40.7794,
    lng: -73.9632,
    blurb: "Five thousand years of art on Fifth Avenue.",
    blurbZh: "第五大道上的五千年藝術史。",
    media: "photo",
    photoQuery: "Metropolitan Museum of Art New York facade",
    costUsd: 30,
    stayMinutes: 150,
    hue: 230,
    emoji: "🖼️",
    handle: "met.daily",
    likes: 36750,
  },
  {
    id: "us-venicebeach",
    country: "us",
    name: "Venice Beach Boardwalk",
    nameZh: "威尼斯海灘步道",
    city: "Los Angeles",
    itemType: "activity",
    lat: 33.985,
    lng: -118.4695,
    blurb: "Skaters, muscle beach and murals along the sand.",
    blurbZh: "滑板、肌肉海灘與沙灘旁的塗鴉牆。",
    media: "insta",
    photoQuery: "Venice Beach boardwalk skatepark Los Angeles",
    costUsd: 0,
    stayMinutes: 90,
    hue: 165,
    emoji: "🛹",
    handle: "venice.local",
    likes: 49328,
  },
];

export function getHomeCountry(code: string): HomeCountry | null {
  return HOME_COUNTRIES.find((c) => c.code === code) ?? null;
}

export function getHomePois(country: HomeCountryCode): HomePoi[] {
  return HOME_POIS.filter((p) => p.country === country);
}

export function getHomePoi(id: string): HomePoi | null {
  return HOME_POIS.find((p) => p.id === id) ?? null;
}

// ─── Itinerary result types (built server-side, rendered client-side) ────────

export interface HomeItineraryStop {
  poiId: string;
  name: string;
  nameZh: string;
  city: string;
  itemType: HomePoiType;
  emoji: string;
  lat: number;
  lng: number;
  /** "HH:MM" local time. */
  arrive: string;
  depart: string;
  costUsd: number;
  /** Pre-formatted local-currency cost, e.g. "¥1,900". */
  costLocal: string;
}

export interface HomeItineraryDay {
  dayNumber: number;
  /** ISO date YYYY-MM-DD. */
  date: string;
  theme: string;
  stops: HomeItineraryStop[];
  dayCostUsd: number;
  travelKm: number;
}

export interface HomeItinerary {
  title: string;
  summary: string;
  country: HomeCountryCode;
  currencyCode: string;
  days: HomeItineraryDay[];
  totalCostUsd: number;
  totalCostLocal: string;
}

/** SSE event payloads streamed by POST /api/home/itinerary. */
export type HomeReasoningStepId = "analyze" | "cluster" | "plan" | "solve" | "cost";

export interface HomeReasoningStepEvent {
  id: HomeReasoningStepId;
  status: "start" | "done" | "fallback";
  detail: string;
}
