import type { AppLocale } from "@/lib/app-locale";

export interface UserGuideSection {
  id: string;
  title: string;
  body: string[];
}

export interface SadSection {
  id: string;
  title: string;
  body: string[];
  /** Optional mono-space block (architecture diagram, pipeline, etc.) */
  diagram?: string;
}

export interface DocsCopy {
  pageTitle: string;
  pageSubtitle: string;
  tocTitle: string;
  sections: {
    api: string;
    schema: string;
    guide: string;
    sad: string;
  };
  api: {
    intro: string;
    methodHeading: string;
    pathHeading: string;
    descHeading: string;
    sourceHeading: string;
    zodBadge: string;
    cronBadge: string;
    noDescription: string;
  };
  schema: {
    intro: string;
    columnHeading: string;
    typeHeading: string;
    modifiersHeading: string;
    createdIn: string;
    columnCount: (n: number) => string;
  };
  guide: {
    intro: string;
    sections: UserGuideSection[];
  };
  sad: {
    intro: string;
    sections: SadSection[];
  };
}

const EN: DocsCopy = {
  pageTitle: "Project documentation",
  pageSubtitle:
    "Auto-generated reference for the TravelSync codebase: APIs, database schema, user guide, and architecture.",
  tocTitle: "On this page",
  sections: {
    api: "API reference",
    schema: "Database schema",
    guide: "User guide",
    sad: "Architecture (SAD)",
  },
  api: {
    intro:
      "All HTTP endpoints under app/api/ are listed below, grouped by surface. The list is generated by walking app/api/**/route.ts at request time, so it always reflects what is actually deployed.",
    methodHeading: "Method",
    pathHeading: "Path",
    descHeading: "Description",
    sourceHeading: "Source",
    zodBadge: "zod",
    cronBadge: "cron",
    noDescription: "—",
  },
  schema: {
    intro:
      "Tables are extracted from supabase/migrations/*.sql. The parser combines the original CREATE TABLE with every ALTER TABLE ADD COLUMN that follows, so the column list reflects the latest migrated state.",
    columnHeading: "Column",
    typeHeading: "Type",
    modifiersHeading: "Modifiers",
    createdIn: "Created in",
    columnCount: (n) => `${n} column${n === 1 ? "" : "s"}`,
  },
  guide: {
    intro:
      "TravelSync is a LINE bot plus a companion web app for planning group trips. Here is how the two surfaces fit together for an end user.",
    sections: [
      {
        id: "guide-getting-started",
        title: "Getting started",
        body: [
          "Add the TravelSync bot to your LINE group. Once it is added, type /start <destination> <dates> (for example, /start Osaka Jul 15-20) in the group chat to create a new trip.",
          "Visit /app/sign-in on this site and log in with LINE. Your trips will appear automatically in the workspace.",
        ],
      },
      {
        id: "guide-home-survey",
        title: "The landing-page trip survey",
        body: [
          "The index page is an interactive survey pipeline. Spin the globe and tap a country marker (Japan, Taiwan or the United States today), zoom into a city, then pick your travel dates on a seasonality-aware calendar: monthly weather, rain days, crowd and price levels, festival windows, quick length presets and a best-window suggestion help you decide when to go. Finally, read the city like a travel magazine: each spot is a full editorial spread — headline, standfirst, fact box and full-bleed photo — and you scroll down through them one at a time (the reader snaps to each spread; arrow keys page too, Enter picks). Stamp the ones you like into the trip; a contents film-strip along the bottom jumps anywhere. When live data is available for the city, places currently trending on Instagram / TikTok open the issue with a \"hot right now\" ribbon — these come from the same social-media trending system that feeds the real itinerary generator, refreshed daily.",
          "Submit your picks and the AI agent plans live on screen: it clusters spots into days shaped to your chosen dates, asks the LLM to theme and order them, runs the real route solver for timings, and estimates costs.",
          "The finished itinerary appears on an animated map with dates, arrive/depart times and expected costs per stop, day and trip. No account is needed; the demo is rate-limited per visitor and nothing is saved.",
        ],
      },
      {
        id: "guide-slash-commands",
        title: "Slash commands in LINE",
        body: [
          "/start — Begin a new trip, with optional destination and date hints.",
          "/add — Add an itinerary item (hotel, restaurant, activity, transport, etc.).",
          "/vote — Open a vote on an item that has multiple options.",
          "/expense — Log a shared expense and split it with the group.",
          "/itinerary — Send the latest trip itinerary back to the group.",
          "/help — Show the full list of supported commands.",
        ],
      },
      {
        id: "guide-free-text",
        title: "Free-text in groups",
        body: [
          "Anything that is not a slash command is treated as free text. The group monitor parses it with Gemini to extract dates, places, flights, hotels, preferences and budget hints.",
          "Detected entities are merged into the trip automatically, so the group can keep chatting naturally without learning a command syntax.",
        ],
      },
      {
        id: "guide-private-chat",
        title: "Private chat with the bot",
        body: [
          "DM the bot to use it as a 1:1 travel concierge. The private-chat service routes requests through the orchestrator and can answer questions, look up flights and hotels, and surface relevant trips you are a member of.",
        ],
      },
      {
        id: "guide-web-app",
        title: "The web workspace",
        body: [
          "Trips — Browse every trip your LINE groups are planning, in one list.",
          "Trip workspace — A shared group chat room is the main view: everyone on the trip talks here alongside your AI planner. As you chat, the AI planner reads the conversation and, when it spots something worth tracking (flight prices, weather, hotel deals, packing, photos), it proposes a bento grid as a card right in the chat — tap Add grid to accept or Not now to dismiss. You can also hover a message: if it's something an agent can handle it shows a small ⚡ chip, and you can drag that message onto the grids rail to create the grid yourself.",
          "Right rail — Your confirmed grids live here at the top; open one to see its latest output. Members and agent chats are in the People section below, and Trip tools links to the overview, itinerary, votes, expenses, ideas, map and packing pages.",
          "Overview canvas — Trip tools → Overview opens a free-form canvas of every feature. Drag tiles anywhere, resize them from the corner, and pan or zoom the board (scroll to pan, ⌘/Ctrl+scroll or the toolbar to zoom, Fit to frame everything). Your arrangement is saved to your account and follows you across devices.",
          "Map — Cross-trip map of every place that has been mentioned.",
          "Templates — Public trip templates you can fork into a new trip.",
          "Inbox — Notifications: reminders, vote outcomes, incidents and digests.",
        ],
      },
      {
        id: "guide-benchmark",
        title: "Itinerary benchmark console",
        body: [
          "Benchmark (/app/benchmark, signed-in users) is the quality lab for the trip generator. Preset scenarios — the same set the CLI uses — appear as cards; hit Run to generate a real itinerary through the production pipeline and score it on seven deterministic metrics (coverage, pace fit, meals, travel efficiency, diversity, vibe match, must-haves) plus an optional LLM judge for day coherence, personalization, realism and title quality.",
          "Custom run lets you define a one-off scenario (destination, days, party, budget, pace, vibes, must-haves) and benchmark it immediately; it is recorded as “adhoc”.",
          "The score-trend chart plots each scenario's deterministic total over time, and the history table below shows every run — web and CLI — with expandable per-metric bars, the judge verdict and reasoning. Runs cost real LLM calls and take 30–120 seconds; each one also creates a private trip template authored by benchmark-runner.",
        ],
      },
      {
        id: "guide-voting",
        title: "Voting and decisions",
        body: [
          "Each trip item can have several options (for example, three candidate hotels). Anyone in the group can open a vote with /vote or from the web app.",
          "Votes close automatically when a majority is reached or when the deadline elapses. Ties trigger a single extension before being resolved.",
        ],
      },
      {
        id: "guide-expenses",
        title: "Expenses and settle-up",
        body: [
          "Log expenses with /expense in LINE or via the Expenses tab in the web app.",
          "Splits can be even, by-share, or by-amount. The web app continuously computes the minimal settle-up transfers so the group always knows who owes whom.",
        ],
      },
      {
        id: "guide-privacy",
        title: "Privacy and data deletion",
        body: [
          "Any group member can leave the trip from the workspace. Organizers can delete a trip from the trip card; this permanently removes itinerary, votes, documents and packing data.",
          "To delete every trace of your account, use the delete button on /app/profile (it calls POST /api/user/delete).",
        ],
      },
    ],
  },
  sad: {
    intro:
      "TravelSync funnels every asynchronous interaction through three chokepoints. This section documents the invariants that the codebase enforces, plus the feature surfaces that exist today.",
    sections: [
      {
        id: "sad-overview",
        title: "System overview",
        body: [
          "TravelSync is a Next.js 16 App Router application deployed on Vercel. Persistence is Supabase Postgres. LINE Messaging API is the primary user-facing surface; a companion web app at /app/* offers richer UI.",
          "All inbound LINE traffic enters through a single signed webhook endpoint. The event is durably queued in the line_events table and processed by a single dispatcher. All outbound LINE messages leave through a single tracked sender. This three-chokepoint design is the most important architectural invariant.",
        ],
        diagram: [
          "LINE → /api/line/webhook (signature verify, idempotent insert)",
          "          │",
          "          ▼",
          "    line_events (durable queue, row per event)",
          "          │  fast path: Next.js after() spawns worker",
          "          ▼",
          "    services/event-processor (single dispatcher)",
          "          │",
          "  ┌───────┼────────────────────┬──────────────────────┐",
          "  ▼       ▼                    ▼                      ▼",
          " slash  free text (groups)  free text (DMs)        postbacks",
          " bot/    services/parsing    services/private-chat   handlePostback",
          "  │       │                    │                      │",
          "  └───────┴────────┬───────────┴──────────────────────┘",
          "                   ▼",
          "          lib/line.ts (sole outbound chokepoint)",
          "                   ▼",
          "          outbound_messages (tracked, retried, backed-off)",
        ].join("\n"),
      },
      {
        id: "sad-inbound",
        title: "Inbound: webhook + durable queue",
        body: [
          "app/api/line/webhook/route.ts verifies the LINE signature, persists every event to line_events keyed by line_event_uid (idempotent), and returns 200 in under one second.",
          "Processing is scheduled via Next.js after() for the happy path. The /api/cron/process-events cron is the recovery sweeper that picks up rows stuck in processing for over five minutes and failed rows whose next_retry_at has elapsed.",
          "Retry backoff is 2^(retry_count+1) seconds, capped at one hour, computed by computeNextRetryAt in services/event-processor.",
        ],
      },
      {
        id: "sad-dispatcher",
        title: "Dispatcher routing rules",
        body: [
          "services/event-processor routes by (event.type, source.type). DMs are detected by lineGroupId === userId.",
          "Slash commands (text.startsWith('/')) → bot/router.ts and the per-command handlers in bot/commands/.",
          "Free text in groups → services/parsing/ (the group monitor, which extracts entities with Gemini).",
          "Free text in 1:1 → services/private-chat/ (LLM reasoning with tool calls via the orchestrator).",
          "Postbacks are not commands. They are handled inside event-processor handlePostback, keyed on a 'prefix|...' data scheme.",
        ],
      },
      {
        id: "sad-outbound",
        title: "Outbound: single sender + tracking",
        body: [
          "lib/line.ts is the only file outside scripts/ that imports @line/bot-sdk. Every push or reply is persisted to outbound_messages with retry count and a next_retry_at, so a failed send can be re-attempted by the cron sweeper.",
          "Notifications are event-sourced: services/notifications/index.ts exposes notifyXxx() wrappers called from feature code. Crons only handle reminders and digests, never the primary delivery path.",
        ],
      },
      {
        id: "sad-features",
        title: "Implemented feature surfaces",
        body: [
          "Trips & itinerary — Trip CRUD, day-by-day itinerary, ideas board, item options with Google Places metadata.",
          "Trip generator — End-to-end itinerary generation from an 8-question survey, shared by the LINE /plan command and the /app/trips/new wizard. See the dedicated section below.",
          "Voting — Per-item votes with deadlines, tie-extensions and automatic closure (services/vote, /api/cron/vote-deadlines).",
          "Expenses — Shared expenses with by-share / by-amount / even splits and continuously-computed settle-up.",
          "Operations — Tracking lists, incidents and follow-ups, daily briefings and digests, transport monitor cron.",
          "Templates — Publishable trip templates with likes, comments, access requests and grants.",
          "Orchestrator — LLM agent with bounded tool calls for the private chat and the in-app plan-master.",
          "Agents — Background agents (services/agents/) for scheduled, autonomous work.",
          "Web workspace — /app/* pages backed by /api/app/* JSON endpoints, with LINE Login and email/password auth. The trip workspace is a shared group chat room (trip_chat_threads kind='group'); posting a message wakes the per-trip orchestrator, which can propose an agent grid via the propose-only grids.add_agent action. Proposals surface as confirm/dismiss cards in the chat and, once confirmed, become custom_grids shown in the right rail. A message can also be classified on demand (POST /api/app/trips/[tripId]/chat/classify, LLM over the agent registry) and, if it maps to an agent, dragged from the chat onto the grids rail (native HTML5 DnD, MIME application/x-chat-task) to create the custom_grid directly — falling back to the prefilled Add-grid dialog when required config is missing.",
          "Trip overview canvas — /app/trips/[tripId]/overview is a free-form pan & zoom canvas (components/app/canvas/). Every feature — hero, itinerary, calendar, budget, tasks, ideas, votes, map, pack, members, and any custom_grids — is a free-floating tile that can be dragged, resized and stacked on an infinite board; the toolbar offers zoom in/out, Fit and Reset. Layout is per-user, per-trip: tile positions/sizes plus the pan/zoom viewport persist to trip_canvas_layouts via GET/PUT /api/app/trips/[tripId]/canvas-layout (upsert on (trip_id, app_user_id)), so a member's board follows them across devices. This replaced the earlier fixed bento grid. The Orchestrator mode toggle (single-goal + structural plan) lives alongside it in components/app/trip-workspace.",
          "Landing survey demo — The public index page is a survey pipeline (globe → city → travel dates → POI media wall → live AI reasoning → animated itinerary map). It is backed by three unauthenticated, per-IP rate-limited routes: POST /api/home/itinerary streams SSE reasoning steps and reuses the production trip-generation solver plus lib/llm for day theming (honoring the picked start date and day count), GET /api/home/poi-photo proxies Google Places photos, and GET /api/home/trending-pois serves live trending cards synthesized from poi_trending_signals + poi_embeddings (services/home-demo/trending-pois.ts) that the wall merges in front of the static catalog in lib/home-survey.ts. Trending cards carry namespaced trend:<place_id> ids; the itinerary and photo routes re-resolve those server-side (with a country check) so client payloads stay untrusted, and everything fails soft to the static catalog. The dates phase is driven by a static seasonal catalog in lib/home-seasons.ts (monthly climate normals, crowd/price levels, festival windows, best-window scoring). Nothing is persisted.",
        ],
      },
      {
        id: "sad-trip-generator",
        title: "Trip generator pipeline",
        body: [
          "services/trip-generation/ is the shared backend for both the LINE /plan command and the web wizard at /app/trips/new. The two entry points feed the same survey state machine and the same generation pipeline; only the UX around them differs.",
          "Survey — Eight typed answers: destination, duration_days, party, party_size, budget_tier, vibe (multi-select), pace and free-text must_haves. The survey step order lives in services/trip-generation/survey.ts and is reused by both surfaces.",
          "Pipeline — A plain typed state machine (deliberately not LangGraph) drives: retrieve POIs → LLM pick assignment → solve route → on infeasibility, structured repair loop (≤ 2 retries) → persist. The LLM never sees opening hours or coordinates; it only emits which placeIds belong on which day. The solver enforces all logistics (open hours, travel time, day-length budget).",
          "Repair loop — When the solver reports an infeasibility (for example, 'Day 2 stop X opens at 10am, can't fit'), the LLM gets the structured report and swaps from the remaining shortlist. After two failed repair rounds the run terminates with GenerationFailedError(\"irreparable\").",
          "Output and fork — Generation always produces a private trip_template first. On the web, POST /api/app/trips/generate immediately forks the template into a real trip and returns the trip id, because the canvas workspace is itself the preview. On LINE the same flow is two postbacks (generate → preview → fork) so the group can confirm before commit.",
          "Failure modes — GenerationFailedError carries a reason (gemini_unavailable, schema_invalid, persist_failed, invalid_answers, no_candidates, irreparable). Gemini calls are wrapped by the global circuit-breaker in lib/gemini.ts.",
          "Trending signals — services/trending/ keeps the POI-picking phase current with social media, fully automatically. A daily cron (/api/cron/trending-pois) collects places currently buzzing on Instagram / TikTok / Reddit / YouTube for destinations with active demand (upcoming trips, recent surveys) plus the landing-page catalog cities as always-eligible seeds, using Gemini's Google Search grounding (no scraping API), a structured extraction pass, and Google Places resolution — unresolvable names are dropped, never guessed. Cold or stale cities also self-heal on demand: services/trending/auto-collect.ts runs a guarded background collection (freshness window, in-flight lock, attempt cooldown) via next/server after() when a public surface serves them. Signals land in poi_trending_signals (one row per destination + place, buzz score 0–1); new places also join the poi_embeddings corpus as source social_trending. During generation, blendTrendingSignals runs after the MLP re-ranker: candidates with a live signal get a recency-decayed similarity boost (7-day half-life, expired at 30 days) plus a 'trending' tag the LLM pick prompt is told about, and up to five hot places the vibe search missed are injected into the shortlist. The whole layer fails open — no signals, no change. Optional manual warm-up: npm run trending:collect -- --destinations 'City, Country'.",
          "POI curation console — /admin/pois (env-gated by ADMIN_BOARD_ENABLED) manages the corpus: every POI carries category (fixed 9-value taxonomy), free-form labels, curation_status (unreviewed / approved / hidden), a manual quality_score prior (0–1) and notes, all metadata-only (never re-embedded). Curation is actionable: hidden POIs are excluded from search_pois_by_vibe and the index-page trending wall. /admin/pois/analytics is the ranking-algorithm workbench: per-POI exposure/selection aggregates from itinerary_feedback (admin_poi_stats RPC), selection rate by shortlist-rank bucket (admin_rank_bucket_stats — does retrieval order predict picks?), the picked-vs-rejected similarity split, rollups by category/source/status/destination, top/under-performer lists and trending-but-never-shortlisted gaps. A deterministic keyword categorizer (POST /api/admin/pois/categorize) bulk-fills missing categories without an LLM.",
          "Quality benchmark — services/trip-generation/benchmark.ts scores any itinerary deterministically (no LLM) on seven weighted metrics: coverage, pace fit, meal coverage, travel efficiency, diversity, vibe alignment and must-haves, aggregated to a 0–100 total. Golden/flawed fixtures under __tests__/evals/fixtures/itinerary/ gate every test run, and `npm run benchmark:itinerary` runs the live pipeline against benchmarks/scenarios.json, scores the persisted template and appends per-metric history to benchmarks/history.jsonl so generator changes can be compared over time. A complementary LLM-as-judge layer (benchmark-judge.ts, routed through lib/llm) grades the subjective qualities rules can't — day coherence, personalization, realism, title/summary quality — on live benchmark runs and, behind RUN_LIVE_EVALS=1, on the golden fixtures. Live runs go through the shared runner (benchmark-runner.ts), which records every run — pass or fail — in the benchmark_runs table; the /app/benchmark page (App API · Benchmark routes: GET scenarios, GET/POST runs, DELETE runs/[id]) lets any signed-in user trigger preset or ad-hoc runs from the browser and charts the score trend from that table.",
        ],
        diagram: [
          "Survey answers (8 keys)",
          "        │",
          "        ▼",
          "  poi-engine.searchPoisByVibe → enrichWithLiveData",
          "        │              route-engine (shortlist of route compositions)",
          "        ▼",
          "  LLM: pick K placeIds per day  (no hours, no coords)",
          "        │",
          "        ▼",
          "  solver.solveItinerary  ─── feasible ──► persist → trip_template",
          "        │                                       │",
          "        │ infeasible (≤ 2 retries)              ▼",
          "        ▼                              fork (web: auto; LINE: postback)",
          "  structured repair report → LLM        ▼",
          "        │ swap from shortlist           trips row",
          "        └──────────────────►",
        ].join("\n"),
      },
      {
        id: "sad-data",
        title: "Data layer",
        body: [
          "All schema changes are timestamped Supabase migrations in supabase/migrations/. lib/database.types.ts is generated from these.",
          "Server code uses createAdminClient() from lib/db.ts (service role). Direct imports of the service-role key are forbidden.",
          "Row-level security is enabled with a default-deny posture (see migration 20260418000000_rls_no_anon_access). All cross-row access goes through the admin client on the server.",
        ],
      },
      {
        id: "sad-jobs",
        title: "Cron jobs",
        body: [
          "Schedules are declared in vercel.json. Each cron route lives under app/api/cron/ and authenticates via the CRON_SECRET header (lib/cron-auth.ts).",
          "Cron is the recovery and time-driven sweeper layer, not the primary delivery path. The list of active jobs is auto-generated above in the API reference section.",
        ],
      },
      {
        id: "sad-design-system",
        title: "Design system & motion",
        body: [
          "Design tokens live in app/globals.css as CSS variables (surfaces, text, borders, status, radius, shadows) mapped into Tailwind v4 via @theme inline. The web app uses a 'vibrant/expressive' language: a LINE-green brand anchor plus a secondary coral/cool/violet axis, gradient tokens (--gradient-brand/-warm/-cool/-aurora), glow shadows, and an animated ambient mesh behind the app shell.",
          "Fonts are loaded with next/font in app/layout.tsx: Space Grotesk (display), Inter (body), JetBrains Mono (numerics), exposed as CSS variables that --font-display/-text/-mono point at.",
          "Motion is centralized in components/motion/. MotionProvider wraps the /app shell with MotionConfig reducedMotion=\"user\"; variants.ts holds the shared fadeUp / stagger / springPop / pageTransition vocabulary; index.tsx exports reusable Reveal, Stagger/StaggerItem, PageTransition and AnimatedNumber helpers built on the 'motion' package (Framer Motion). CSS keyframes in globals.css cover the rest (skeleton shimmer, aurora pan, tile glow, bento cascade).",
          "Accessibility: every animation degrades under prefers-reduced-motion — the global CSS block collapses transitions to ~0ms and MotionConfig neutralizes transform/layout animations.",
        ],
      },
    ],
  },
};

const ZH_TW: DocsCopy = {
  pageTitle: "專案技術文件",
  pageSubtitle: "TravelSync 程式碼自動生成的參考文件：API、資料庫結構、使用指南與系統架構。",
  tocTitle: "本頁目錄",
  sections: {
    api: "API 參考",
    schema: "資料庫結構",
    guide: "使用指南",
    sad: "系統架構文件 (SAD)",
  },
  api: {
    intro:
      "下方列出 app/api/ 底下所有 HTTP 端點，依模組分組。內容於請求時掃描 app/api/**/route.ts 自動生成，永遠反映目前部署的版本。",
    methodHeading: "方法",
    pathHeading: "路徑",
    descHeading: "說明",
    sourceHeading: "原始碼",
    zodBadge: "zod",
    cronBadge: "cron",
    noDescription: "—",
  },
  schema: {
    intro:
      "資料表來自 supabase/migrations/*.sql。剖析器會合併原始 CREATE TABLE 與之後的 ALTER TABLE ADD COLUMN，因此欄位列表反映目前的 migration 狀態。",
    columnHeading: "欄位",
    typeHeading: "型別",
    modifiersHeading: "修飾子",
    createdIn: "建立於",
    columnCount: (n) => `${n} 個欄位`,
  },
  guide: {
    intro: "TravelSync 是一個 LINE 機器人，加上一個搭配的 Web App 用來規劃團體旅行。以下說明兩個介面如何協同運作。",
    sections: [
      {
        id: "guide-getting-started",
        title: "開始使用",
        body: [
          "把 TravelSync 機器人加入你的 LINE 群組。加入後在群組裡輸入 /start <目的地> <日期>（例如 /start Osaka Jul 15-20）即可建立一個新旅程。",
          "在本網站造訪 /app/sign-in 並以 LINE 登入。你的旅程會自動出現在工作區裡。",
        ],
      },
      {
        id: "guide-home-survey",
        title: "首頁互動式行程問卷",
        body: [
          "首頁本身就是一條互動式問卷流程。轉動地球並點選國家圖釘（目前提供日本、台灣與美國），放大到城市後，先在懂季節的月曆上挑選旅遊日期：每月天氣、降雨天數、人潮與價格等級、節慶時段、快速天數選項與最佳時段建議，幫你決定何時出發。最後像讀旅遊雜誌一樣瀏覽城市：每個景點都是一整頁編輯專題 — 大標、引言、資訊欄與滿版照片 — 往下捲動一次看一個（閱讀器會自動對齊每一頁；方向鍵也能翻頁，Enter 選入）。喜歡的蓋章收入行程；底部的目錄縮圖列可隨時跳頁。若該城市有即時資料，目前在 Instagram / TikTok 上發燒的地點會以「現正爆紅」緞帶開場 — 這些來自與正式行程生成器共用的社群趨勢系統，每日更新。",
          "送出選擇後，AI 代理會在畫面上即時規劃：把景點依你選的日期分天、請 LLM 命名與排序每一天、用正式的路線求解器模擬時間，最後估算花費。",
          "完成的行程會呈現在動態地圖上，包含日期、抵達/離開時間，以及每站、每日與整趟旅程的預估花費。不需註冊帳號；此示範依訪客限流且不會儲存任何資料。",
        ],
      },
      {
        id: "guide-slash-commands",
        title: "LINE 斜線指令",
        body: [
          "/start — 建立新旅程，可附帶目的地與日期提示。",
          "/add — 加入行程項目（住宿、餐廳、活動、交通等）。",
          "/vote — 對含有多個選項的項目發起投票。",
          "/expense — 紀錄共同支出並與群組分帳。",
          "/itinerary — 將最新的行程回傳到群組。",
          "/help — 顯示所有支援的指令。",
        ],
      },
      {
        id: "guide-free-text",
        title: "群組中的自由訊息",
        body: [
          "任何非斜線指令的訊息都會被視為自由文字。群組監聽器會使用 Gemini 從中抽取日期、地點、航班、住宿、偏好與預算等資訊。",
          "抽取到的實體會自動合併到旅程中，群組可以用自然對話的方式持續討論，不需要學任何指令語法。",
        ],
      },
      {
        id: "guide-private-chat",
        title: "與機器人私訊",
        body: [
          "直接私訊機器人即可作為一對一的旅遊助理。私訊服務會走 orchestrator，可以回答問題、查詢航班與住宿，並把你所屬旅程的相關內容一併帶出。",
        ],
      },
      {
        id: "guide-web-app",
        title: "Web 工作區",
        body: [
          "旅程 — 一次瀏覽所有 LINE 群組正在規劃中的旅程。",
          "旅程工作區 — 主畫面是共用的群組聊天室：所有成員與 AI 規劃助手都在這裡對話。當你們聊天時，AI 規劃助手會閱讀對話，發現值得追蹤的事項（機票價格、天氣、飯店優惠、打包、照片）時，會直接在聊天中以卡片形式建議一個 bento 格子 — 點「新增格子」接受，或「暫時不要」忽略。你也可以把游標移到訊息上：若該訊息是某個代理人能處理的任務，會顯示一個 ⚡ 標記，將該訊息拖曳到右側欄的格子區即可自行建立對應的格子。",
          "右側欄 — 已確認的格子顯示在最上方，點開即可查看最新結果。成員與代理人對話在下方的「成員」區，而「旅程工具」連到總覽、行程、投票、支出、點子、地圖與打包頁面。",
          "總覽畫布 — 「旅程工具 → 總覽」會開啟一個自由排列的畫布，涵蓋所有功能。你可以把格子拖到任意位置、從右下角調整大小，並平移或縮放整個畫布（滾動平移、⌘/Ctrl+滾動或工具列縮放，「Fit」可一次框住全部）。你的排列會存到你的帳號，並在各裝置間同步。",
          "地圖 — 跨旅程地圖，顯示曾被提及的所有地點。",
          "範本 — 公開的旅程範本，可一鍵 Fork 成新旅程。",
          "收件匣 — 通知：提醒、投票結果、事件處理與摘要。",
        ],
      },
      {
        id: "guide-benchmark",
        title: "行程基準測試主控台",
        body: [
          "基準測試（/app/benchmark，需登入）是旅程生成器的品質實驗室。預設情境（與 CLI 使用同一組）以卡片呈現；按「執行」即透過正式管線生成真實行程，並以七項確定性指標（天數覆蓋、節奏契合、用餐安排、移動效率、多樣性、氛圍契合、必備項目）打分，可另啟用 LLM 評審評估每日連貫性、個人化、可執行性與標題品質。",
          "「自訂執行」可定義一次性情境（目的地、天數、同行類型、預算、節奏、氛圍、必備項目）並立即測試，紀錄會標為「adhoc」。",
          "分數趨勢圖繪出各情境確定性總分的時間變化；下方歷史表列出所有執行（Web 與 CLI），可展開查看逐指標長條、評審結果與評語。每次執行都會呼叫真實 LLM、約需 30–120 秒，並會產生一個由 benchmark-runner 建立的私人旅程範本。",
        ],
      },
      {
        id: "guide-voting",
        title: "投票與決策",
        body: [
          "每個旅程項目可以有多個選項（例如三間候選飯店）。任何成員都可以用 /vote 或在 Web App 中發起投票。",
          "達到多數決或截止時間時投票會自動關閉。平手會觸發一次延長，再無法決定就以系統規則收斂。",
        ],
      },
      {
        id: "guide-expenses",
        title: "支出與分帳",
        body: [
          "用 /expense 或 Web App 的支出頁面紀錄一筆共同支出。",
          "支援平均分攤、按份數、按金額三種分帳方式。Web App 會持續計算最少的轉帳次數，群組永遠知道誰該付誰多少。",
        ],
      },
      {
        id: "guide-privacy",
        title: "隱私與資料刪除",
        body: [
          "成員可以從工作區自行離開旅程。組織者可以從旅程卡片刪除旅程，這會永久移除行程、投票、文件與打包資料。",
          "若要刪除全部帳號資料，可在 /app/profile 使用刪除按鈕（會呼叫 POST /api/user/delete）。",
        ],
      },
    ],
  },
  sad: {
    intro:
      "TravelSync 所有非同步互動都會經過三個關鍵節點。本節記錄程式碼層面強制執行的不變條件，以及目前已實作的功能模組。",
    sections: [
      {
        id: "sad-overview",
        title: "系統概觀",
        body: [
          "TravelSync 是部署在 Vercel 上的 Next.js 16 App Router 應用，資料儲存在 Supabase Postgres。LINE Messaging API 是主要面對使用者的介面；/app/* 下的 Web App 提供更完整的 UI。",
          "所有來自 LINE 的訊息只會經過一個簽章驗證過的 webhook 端點；事件持久化在 line_events 資料表，再交由唯一的 dispatcher 處理；所有出站訊息都由唯一的 sender 發出。這個三節點設計是最重要的架構不變條件。",
        ],
        diagram: [
          "LINE → /api/line/webhook（驗章、Idempotent insert）",
          "          │",
          "          ▼",
          "    line_events（持久化 queue，每筆事件一列）",
          "          │  Fast path：Next.js after() 觸發 worker",
          "          ▼",
          "    services/event-processor（唯一 dispatcher）",
          "          │",
          "  ┌───────┼────────────────────┬──────────────────────┐",
          "  ▼       ▼                    ▼                      ▼",
          " 斜線指令 群組自由文字          私訊自由文字            Postback",
          " bot/    services/parsing    services/private-chat   handlePostback",
          "  │       │                    │                      │",
          "  └───────┴────────┬───────────┴──────────────────────┘",
          "                   ▼",
          "          lib/line.ts（唯一出站節點）",
          "                   ▼",
          "          outbound_messages（追蹤、重試、指數退避）",
        ].join("\n"),
      },
      {
        id: "sad-inbound",
        title: "入站：webhook + 持久化 queue",
        body: [
          "app/api/line/webhook/route.ts 驗證 LINE 簽章、以 line_event_uid 作為冪等鍵將事件寫入 line_events，並在一秒內回 200。",
          "處理用 Next.js 的 after() 排程為 happy path。/api/cron/process-events 是回收 sweeper，會撿回卡在 processing 超過 5 分鐘的列，以及 next_retry_at 已到的 failed 列。",
          "重試 backoff 為 2^(retry_count+1) 秒，上限 1 小時，由 services/event-processor 的 computeNextRetryAt 計算。",
        ],
      },
      {
        id: "sad-dispatcher",
        title: "Dispatcher 路由規則",
        body: [
          "services/event-processor 依 (event.type, source.type) 派發。私訊判斷：lineGroupId === userId。",
          "斜線指令（text.startsWith('/')）→ bot/router.ts，再進入 bot/commands/ 各自的 handler。",
          "群組自由文字 → services/parsing/（群組監聽器，由 Gemini 抽取實體）。",
          "私訊自由文字 → services/private-chat/（透過 orchestrator 進行 LLM 推理與工具呼叫）。",
          "Postback 不是指令，由 event-processor 的 handlePostback 以 'prefix|...' 形式的 data 解析。",
        ],
      },
      {
        id: "sad-outbound",
        title: "出站：唯一 sender + 追蹤",
        body: [
          "lib/line.ts 是 scripts/ 之外唯一引用 @line/bot-sdk 的檔案。每次 push 或 reply 都會寫入 outbound_messages，包含 retry_count 與 next_retry_at；失敗的訊息會由 cron sweeper 接手重送。",
          "通知是事件驅動：services/notifications/index.ts 提供 notifyXxx() 系列函式由業務碼呼叫。Cron 只處理提醒與摘要，永遠不是主要遞送路徑。",
        ],
      },
      {
        id: "sad-features",
        title: "已實作的功能模組",
        body: [
          "旅程與行程 — 旅程 CRUD、逐日行程、想法看板、含 Google Places 中繼資料的選項。",
          "旅程生成器 — 由 8 題問卷端到端生成完整行程，LINE /plan 指令與 /app/trips/new 精靈共用同一條管線。詳見下方專章。",
          "投票 — 帶截止時間的項目投票、平手延長機制、自動關閉（services/vote、/api/cron/vote-deadlines）。",
          "支出 — 共同支出，支援按份數／按金額／平均分帳，並持續計算最少轉帳次數。",
          "營運 — 追蹤清單、事件處理與後續追蹤、每日 briefing 與摘要、交通監控 cron。",
          "範本 — 可發佈的旅程範本，含 Like、留言、存取請求與授權。",
          "Orchestrator — 為私訊與 Web App 計畫管理用的 LLM agent，含工具呼叫上限。",
          "Agents — services/agents/ 底下的常駐型自動代理人。",
          "Web 工作區 — /app/* 頁面背後是 /api/app/* JSON 端點，支援 LINE Login 與 Email/Password 登入。旅程工作區是一個共用的群組聊天室（trip_chat_threads kind='group'）；發送訊息會喚醒該旅程的 orchestrator，它可透過 propose-only 的 grids.add_agent 動作建議一個代理人格子。建議會以確認／忽略卡片的形式出現在聊天中，確認後即成為顯示在右側欄的 custom_grids。訊息也可以即時分類（POST /api/app/trips/[tripId]/chat/classify，以 LLM 比對代理人清單）；若對應到某個代理人，便可從聊天直接拖曳到右側欄格子區（原生 HTML5 拖放，MIME application/x-chat-task）以直接建立 custom_grid，若缺少必填設定則退回預先填好的新增格子對話框。",
          "旅程總覽畫布 — /app/trips/[tripId]/overview 是一個自由平移縮放的畫布（components/app/canvas/）。每個功能 — hero、行程、行事曆、預算、任務、點子、投票、地圖、打包、成員，以及任何 custom_grids — 都是可在無限畫布上拖曳、調整大小與堆疊的浮動格子；工具列提供放大／縮小、Fit 與 Reset。版面是「每位使用者、每趟旅程」獨立：格子的位置／大小與平移縮放 viewport 會透過 GET/PUT /api/app/trips/[tripId]/canvas-layout 存到 trip_canvas_layouts（以 (trip_id, app_user_id) upsert），因此成員的畫布會在各裝置間同步。此設計取代了先前固定的 bento 格線。Orchestrator 模式（單一目標＋結構化計畫）的切換位於 components/app/trip-workspace，與其並列。",
          "首頁問卷示範 — 公開首頁是一條問卷流程（地球 → 城市 → 旅遊日期 → 景點媒體牆 → AI 即時推理 → 動態行程地圖）。背後是三個免登入、依 IP 限流的端點：POST /api/home/itinerary 以 SSE 串流推理步驟，重用正式的 trip-generation 求解器並透過 lib/llm 為每日命名（並尊重所選的出發日與天數）；GET /api/home/poi-photo 代理 Google Places 照片；GET /api/home/trending-pois 由 poi_trending_signals + poi_embeddings 即時合成社群趨勢卡片（services/home-demo/trending-pois.ts），媒體牆會把它們排在 lib/home-survey.ts 靜態目錄之前。趨勢卡片使用 trend:<place_id> 命名空間 id；itinerary 與 photo 端點都會在伺服器端重新解析（並檢查國家），客戶端 payload 永不被信任，任何失敗都會軟性退回靜態目錄。日期階段由 lib/home-seasons.ts 的靜態季節目錄驅動（每月氣候常態、人潮/價格等級、節慶時段與最佳時段評分）。不儲存任何資料。",
        ],
      },
      {
        id: "sad-trip-generator",
        title: "旅程生成器 Pipeline",
        body: [
          "services/trip-generation/ 是 LINE /plan 指令與 Web 精靈 /app/trips/new 共用的後端。兩個入口走同一條問卷狀態機與同一條生成管線，只有外層 UX 不同。",
          "問卷 — 共 8 題類型化答案：destination、duration_days、party、party_size、budget_tier、vibe（複選）、pace 與自由文字 must_haves。題目順序定義於 services/trip-generation/survey.ts，兩個介面共用。",
          "Pipeline — 一個樸素的型別化狀態機（刻意不用 LangGraph）：retrieve POIs → LLM 指派 → solver 排線 → 若不可行則進入結構化 repair 迴圈（≤ 2 次重試）→ 持久化。LLM 看不到營業時間或座標，只輸出哪幾個 placeId 屬於哪一天；solver 負責所有物流（營業時間、移動時間、單日預算）。",
          "Repair 迴圈 — 當 solver 回報不可行（例如 'Day 2 X 點 10am 才開門，塞不下'），LLM 會拿到結構化報告並從候補清單中替換。連續兩次仍不可行時以 GenerationFailedError(\"irreparable\") 結束。",
          "輸出與 Fork — 生成永遠先產出一個 private trip_template。Web 端的 POST /api/app/trips/generate 會立即把 template fork 成正式 trip 並回傳 trip id，因為畫布工作區本身就是預覽；LINE 端則拆成兩個 postback（generate → preview → fork），讓群組先確認再寫入。",
          "失敗類別 — GenerationFailedError 帶有 reason（gemini_unavailable、schema_invalid、persist_failed、invalid_answers、no_candidates、irreparable）。所有 Gemini 呼叫都包在 lib/gemini.ts 的全域 circuit-breaker 之中。",
          "社群趨勢訊號 — services/trending/ 讓 POI 挑選階段跟上社群媒體，完全自動化。每日 cron（/api/cron/trending-pois）針對有實際需求的目的地（即將出發的旅程、近期問卷）加上首頁目錄城市（常駐種子）收集目前在 Instagram / TikTok / Reddit / YouTube 上發燒的地點：先用 Gemini 內建 Google Search grounding（無需爬蟲 API），再經結構化抽取，最後以 Google Places 解析成真實 place_id — 解析不到的名稱直接捨棄，絕不猜測。冷門或過期的城市也會自我修復：當公開介面提供該城市時，services/trending/auto-collect.ts 會透過 next/server after() 執行帶防護的背景收集（新鮮度視窗、進行中鎖、重試冷卻）。訊號寫入 poi_trending_signals（每個目的地 + 地點一列，buzz 分數 0–1）；語料庫沒有的新地點同時以 source social_trending 寫入 poi_embeddings。生成時 blendTrendingSignals 在 MLP re-ranker 之後執行：帶有有效訊號的候選會獲得隨時間衰減的相似度加成（半衰期 7 天、30 天過期）並加上 trending 標籤（LLM 挑選提示詞已知悉），vibe 檢索漏掉的熱門地點最多注入 5 個。整層 fail open — 沒有訊號就完全不影響。也可選擇手動預熱：npm run trending:collect -- --destinations 'City, Country'。",
          "POI 策展主控台 — /admin/pois（由 ADMIN_BOARD_ENABLED 環境變數把關）管理整個語料庫：每個 POI 帶有 category（固定 9 類分類法）、自由 labels、curation_status（unreviewed / approved / hidden）、人工 quality_score 先驗（0–1）與備註，全部只是 metadata（不會觸發重新嵌入）。策展會實際生效：hidden 的 POI 會從 search_pois_by_vibe 與首頁趨勢牆排除。/admin/pois/analytics 是排名演算法工作台：來自 itinerary_feedback 的逐 POI 曝光／被選聚合（admin_poi_stats RPC）、依候選名單排名分桶的被選率（admin_rank_bucket_stats — 檢索排序是否預測 LLM 挑選）、被選 vs 被拒的相似度差、依 category／source／status／目的地的彙總、最佳／最差表現清單，以及「有社群熱度但從未進候選名單」的缺口。另有確定性關鍵字分類器（POST /api/admin/pois/categorize）可一鍵補齊缺漏的 category，無需 LLM。",
          "品質基準測試 — services/trip-generation/benchmark.ts 以確定性方式（不呼叫 LLM）對任何行程打分：coverage、pace fit、meal coverage、travel efficiency、diversity、vibe alignment、must-haves 七項加權指標，彙總為 0–100 總分。__tests__/evals/fixtures/itinerary/ 下的黃金／瑕疵 fixture 在每次測試都會把關；`npm run benchmark:itinerary` 則以 benchmarks/scenarios.json 跑真實管線、對持久化後的 template 打分，並將逐指標歷史寫入 benchmarks/history.jsonl，讓生成器的改動可以跨時間比較。另有互補的 LLM 評審層（benchmark-judge.ts，經由 lib/llm 路由），評分規則量不到的主觀品質 — 每日連貫性、個人化程度、可執行性、標題／摘要品質 — 於 live benchmark 執行時預設啟用，並在 RUN_LIVE_EVALS=1 時對黃金 fixture 把關。Live 執行統一走共用 runner（benchmark-runner.ts），每次執行（無論成敗）都記錄到 benchmark_runs 資料表；/app/benchmark 頁面（App API · Benchmark 路由：GET scenarios、GET/POST runs、DELETE runs/[id]）讓登入使用者直接在瀏覽器觸發預設或自訂執行，並以該表繪製分數趨勢。",
        ],
        diagram: [
          "問卷答案 (8 個欄位)",
          "        │",
          "        ▼",
          "  poi-engine.searchPoisByVibe → enrichWithLiveData",
          "        │              route-engine（route 組合候補）",
          "        ▼",
          "  LLM：每日選 K 個 placeId（無時間、無座標）",
          "        │",
          "        ▼",
          "  solver.solveItinerary  ─── 可行 ──► 寫入 trip_template",
          "        │                                       │",
          "        │ 不可行（≤ 2 次重試）                  ▼",
          "        ▼                              Fork（Web：自動；LINE：postback）",
          "  結構化 repair report → LLM             ▼",
          "        │ 從候補清單替換                 trips 列",
          "        └──────────────────►",
        ].join("\n"),
      },
      {
        id: "sad-data",
        title: "資料層",
        body: [
          "所有 schema 變更都是 supabase/migrations/ 底下時間戳命名的 migration。lib/database.types.ts 從這些 migration 自動產生。",
          "Server 端使用 lib/db.ts 的 createAdminClient()（service role）。禁止直接引用 service-role key。",
          "Row-level security 預設拒絕（見 20260418000000_rls_no_anon_access）。所有跨列存取都在 server 上透過 admin client 進行。",
        ],
      },
      {
        id: "sad-jobs",
        title: "Cron 任務",
        body: [
          "排程在 vercel.json 中宣告。每個 cron route 位於 app/api/cron/ 底下，透過 CRON_SECRET header 驗證（lib/cron-auth.ts）。",
          "Cron 是回收與時間驅動的 sweeper 層，不是主要遞送路徑。目前啟用中的 cron 列表會自動出現在上方 API 參考章節。",
        ],
      },
      {
        id: "sad-design-system",
        title: "設計系統與動效",
        body: [
          "設計 token 以 CSS 變數定義於 app/globals.css（表面、文字、邊框、狀態、圓角、陰影），並透過 Tailwind v4 的 @theme inline 對應為工具類別。Web app 採用「鮮明／表現力」風格：以 LINE 綠為品牌主軸，輔以珊瑚／冷色／紫色次要色軸、漸層 token（--gradient-brand/-warm/-cool/-aurora）、光暈陰影，以及 app shell 背後的動態 ambient mesh。",
          "字型透過 app/layout.tsx 的 next/font 載入：Space Grotesk（標題）、Inter（內文）、JetBrains Mono（數字），以 CSS 變數提供，並由 --font-display/-text/-mono 指向。",
          "動效集中於 components/motion/。MotionProvider 以 MotionConfig reducedMotion=\"user\" 包覆 /app shell；variants.ts 收斂共用的 fadeUp / stagger / springPop / pageTransition 詞彙；index.tsx 匯出可重用的 Reveal、Stagger/StaggerItem、PageTransition 與 AnimatedNumber，皆建構於 'motion' 套件（Framer Motion）。其餘動效由 globals.css 的 CSS keyframes 提供（skeleton 微光、aurora 漸層流動、tile glow、bento 串接進場）。",
          "無障礙：所有動畫在 prefers-reduced-motion 下都會退化——全域 CSS 區塊將過場壓縮為約 0ms，MotionConfig 也會停用 transform/layout 動畫。",
        ],
      },
    ],
  },
};

export function getDocsCopy(locale: AppLocale): DocsCopy {
  return locale === "zh-TW" ? ZH_TW : EN;
}
