import type { AppLocale } from "@/lib/app-locale";

export interface UserGuideSection {
  id: string;
  title: string;
  body: string[];
}

export interface SadSection {
  id: string;
  title: string;
  body: string[];
  /** Optional mono-space block (architecture diagram, pipeline, etc.) */
  diagram?: string;
}

export interface DocsCopy {
  pageTitle: string;
  pageSubtitle: string;
  tocTitle: string;
  sections: {
    api: string;
    schema: string;
    guide: string;
    sad: string;
  };
  api: {
    intro: string;
    methodHeading: string;
    pathHeading: string;
    descHeading: string;
    sourceHeading: string;
    zodBadge: string;
    cronBadge: string;
    noDescription: string;
  };
  schema: {
    intro: string;
    columnHeading: string;
    typeHeading: string;
    modifiersHeading: string;
    createdIn: string;
    columnCount: (n: number) => string;
  };
  guide: {
    intro: string;
    sections: UserGuideSection[];
  };
  sad: {
    intro: string;
    sections: SadSection[];
  };
}

const EN: DocsCopy = {
  pageTitle: "Project documentation",
  pageSubtitle:
    "Auto-generated reference for the TravelSync codebase: APIs, database schema, user guide, and architecture.",
  tocTitle: "On this page",
  sections: {
    api: "API reference",
    schema: "Database schema",
    guide: "User guide",
    sad: "Architecture (SAD)",
  },
  api: {
    intro:
      "All HTTP endpoints under app/api/ are listed below, grouped by surface. The list is generated by walking app/api/**/route.ts at request time, so it always reflects what is actually deployed.",
    methodHeading: "Method",
    pathHeading: "Path",
    descHeading: "Description",
    sourceHeading: "Source",
    zodBadge: "zod",
    cronBadge: "cron",
    noDescription: "—",
  },
  schema: {
    intro:
      "Tables are extracted from supabase/migrations/*.sql. The parser combines the original CREATE TABLE with every ALTER TABLE ADD COLUMN that follows, so the column list reflects the latest migrated state.",
    columnHeading: "Column",
    typeHeading: "Type",
    modifiersHeading: "Modifiers",
    createdIn: "Created in",
    columnCount: (n) => `${n} column${n === 1 ? "" : "s"}`,
  },
  guide: {
    intro:
      "TravelSync is a LINE bot plus a companion web app for planning group trips. Here is how the two surfaces fit together for an end user.",
    sections: [
      {
        id: "guide-getting-started",
        title: "Getting started",
        body: [
          "Add the TravelSync bot to your LINE group. Once it is added, type /start <destination> <dates> (for example, /start Osaka Jul 15-20) in the group chat to create a new trip.",
          "Visit /app/sign-in on this site and log in with LINE. Your trips will appear automatically in the workspace.",
        ],
      },
      {
        id: "guide-home-survey",
        title: "The landing-page trip survey",
        body: [
          "The index page is an interactive survey pipeline. Spin the globe and tap a country marker (Japan, Taiwan or the United States today), then pick the spots that catch your eye from a wall of photos, video tiles and social posts.",
          "Submit your picks and the AI agent plans live on screen: it clusters spots into days, asks the LLM to theme and order them, runs the real route solver for timings, and estimates costs.",
          "The finished itinerary appears on an animated map with dates, arrive/depart times and expected costs per stop, day and trip. No account is needed; the demo is rate-limited per visitor and nothing is saved.",
        ],
      },
      {
        id: "guide-slash-commands",
        title: "Slash commands in LINE",
        body: [
          "/start — Begin a new trip, with optional destination and date hints.",
          "/add — Add an itinerary item (hotel, restaurant, activity, transport, etc.).",
          "/vote — Open a vote on an item that has multiple options.",
          "/expense — Log a shared expense and split it with the group.",
          "/itinerary — Send the latest trip itinerary back to the group.",
          "/help — Show the full list of supported commands.",
        ],
      },
      {
        id: "guide-free-text",
        title: "Free-text in groups",
        body: [
          "Anything that is not a slash command is treated as free text. The group monitor parses it with Gemini to extract dates, places, flights, hotels, preferences and budget hints.",
          "Detected entities are merged into the trip automatically, so the group can keep chatting naturally without learning a command syntax.",
        ],
      },
      {
        id: "guide-private-chat",
        title: "Private chat with the bot",
        body: [
          "DM the bot to use it as a 1:1 travel concierge. The private-chat service routes requests through the orchestrator and can answer questions, look up flights and hotels, and surface relevant trips you are a member of.",
        ],
      },
      {
        id: "guide-web-app",
        title: "The web workspace",
        body: [
          "Trips — Browse every trip your LINE groups are planning, in one list.",
          "Trip workspace — A shared group chat room is the main view: everyone on the trip talks here alongside your AI planner. As you chat, the AI planner reads the conversation and, when it spots something worth tracking (flight prices, weather, hotel deals, packing, photos), it proposes a bento grid as a card right in the chat — tap Add grid to accept or Not now to dismiss. You can also hover a message: if it's something an agent can handle it shows a small ⚡ chip, and you can drag that message onto the grids rail to create the grid yourself.",
          "Right rail — Your confirmed grids live here at the top; open one to see its latest output. Members and agent chats are in the People section below, and Trip tools links to the overview, itinerary, votes, expenses, ideas, map and packing pages.",
          "Map — Cross-trip map of every place that has been mentioned.",
          "Templates — Public trip templates you can fork into a new trip.",
          "Inbox — Notifications: reminders, vote outcomes, incidents and digests.",
        ],
      },
      {
        id: "guide-voting",
        title: "Voting and decisions",
        body: [
          "Each trip item can have several options (for example, three candidate hotels). Anyone in the group can open a vote with /vote or from the web app.",
          "Votes close automatically when a majority is reached or when the deadline elapses. Ties trigger a single extension before being resolved.",
        ],
      },
      {
        id: "guide-expenses",
        title: "Expenses and settle-up",
        body: [
          "Log expenses with /expense in LINE or via the Expenses tab in the web app.",
          "Splits can be even, by-share, or by-amount. The web app continuously computes the minimal settle-up transfers so the group always knows who owes whom.",
        ],
      },
      {
        id: "guide-privacy",
        title: "Privacy and data deletion",
        body: [
          "Any group member can leave the trip from the workspace. Organizers can delete a trip from the trip card; this permanently removes itinerary, votes, documents and packing data.",
          "To delete every trace of your account, use the delete button on /app/profile (it calls POST /api/user/delete).",
        ],
      },
    ],
  },
  sad: {
    intro:
      "TravelSync funnels every asynchronous interaction through three chokepoints. This section documents the invariants that the codebase enforces, plus the feature surfaces that exist today.",
    sections: [
      {
        id: "sad-overview",
        title: "System overview",
        body: [
          "TravelSync is a Next.js 16 App Router application deployed on Vercel. Persistence is Supabase Postgres. LINE Messaging API is the primary user-facing surface; a companion web app at /app/* offers richer UI.",
          "All inbound LINE traffic enters through a single signed webhook endpoint. The event is durably queued in the line_events table and processed by a single dispatcher. All outbound LINE messages leave through a single tracked sender. This three-chokepoint design is the most important architectural invariant.",
        ],
        diagram: [
          "LINE → /api/line/webhook (signature verify, idempotent insert)",
          "          │",
          "          ▼",
          "    line_events (durable queue, row per event)",
          "          │  fast path: Next.js after() spawns worker",
          "          ▼",
          "    services/event-processor (single dispatcher)",
          "          │",
          "  ┌───────┼────────────────────┬──────────────────────┐",
          "  ▼       ▼                    ▼                      ▼",
          " slash  free text (groups)  free text (DMs)        postbacks",
          " bot/    services/parsing    services/private-chat   handlePostback",
          "  │       │                    │                      │",
          "  └───────┴────────┬───────────┴──────────────────────┘",
          "                   ▼",
          "          lib/line.ts (sole outbound chokepoint)",
          "                   ▼",
          "          outbound_messages (tracked, retried, backed-off)",
        ].join("\n"),
      },
      {
        id: "sad-inbound",
        title: "Inbound: webhook + durable queue",
        body: [
          "app/api/line/webhook/route.ts verifies the LINE signature, persists every event to line_events keyed by line_event_uid (idempotent), and returns 200 in under one second.",
          "Processing is scheduled via Next.js after() for the happy path. The /api/cron/process-events cron is the recovery sweeper that picks up rows stuck in processing for over five minutes and failed rows whose next_retry_at has elapsed.",
          "Retry backoff is 2^(retry_count+1) seconds, capped at one hour, computed by computeNextRetryAt in services/event-processor.",
        ],
      },
      {
        id: "sad-dispatcher",
        title: "Dispatcher routing rules",
        body: [
          "services/event-processor routes by (event.type, source.type). DMs are detected by lineGroupId === userId.",
          "Slash commands (text.startsWith('/')) → bot/router.ts and the per-command handlers in bot/commands/.",
          "Free text in groups → services/parsing/ (the group monitor, which extracts entities with Gemini).",
          "Free text in 1:1 → services/private-chat/ (LLM reasoning with tool calls via the orchestrator).",
          "Postbacks are not commands. They are handled inside event-processor handlePostback, keyed on a 'prefix|...' data scheme.",
        ],
      },
      {
        id: "sad-outbound",
        title: "Outbound: single sender + tracking",
        body: [
          "lib/line.ts is the only file outside scripts/ that imports @line/bot-sdk. Every push or reply is persisted to outbound_messages with retry count and a next_retry_at, so a failed send can be re-attempted by the cron sweeper.",
          "Notifications are event-sourced: services/notifications/index.ts exposes notifyXxx() wrappers called from feature code. Crons only handle reminders and digests, never the primary delivery path.",
        ],
      },
      {
        id: "sad-features",
        title: "Implemented feature surfaces",
        body: [
          "Trips & itinerary — Trip CRUD, day-by-day itinerary, ideas board, item options with Google Places metadata.",
          "Trip generator — End-to-end itinerary generation from an 8-question survey, shared by the LINE /plan command and the /app/trips/new wizard. See the dedicated section below.",
          "Voting — Per-item votes with deadlines, tie-extensions and automatic closure (services/vote, /api/cron/vote-deadlines).",
          "Expenses — Shared expenses with by-share / by-amount / even splits and continuously-computed settle-up.",
          "Operations — Tracking lists, incidents and follow-ups, daily briefings and digests, transport monitor cron.",
          "Templates — Publishable trip templates with likes, comments, access requests and grants.",
          "Orchestrator — LLM agent with bounded tool calls for the private chat and the in-app plan-master.",
          "Agents — Background agents (services/agents/) for scheduled, autonomous work.",
          "Web workspace — /app/* pages backed by /api/app/* JSON endpoints, with LINE Login and email/password auth. The trip workspace is a shared group chat room (trip_chat_threads kind='group'); posting a message wakes the per-trip orchestrator, which can propose a bento grid via the propose-only grids.add_agent action. Proposals surface as confirm/dismiss cards in the chat and, once confirmed, become custom_grids shown in the right rail. A message can also be classified on demand (POST /api/app/trips/[tripId]/chat/classify, LLM over the agent registry) and, if it maps to an agent, dragged from the chat onto the grids rail (native HTML5 DnD, MIME application/x-chat-task) to create the custom_grid directly — falling back to the prefilled Add-grid dialog when required config is missing.",
          "Landing survey demo — The public index page is a four-phase survey pipeline (globe → POI media wall → live AI reasoning → animated itinerary map). It is backed by two unauthenticated, per-IP rate-limited routes: POST /api/home/itinerary streams SSE reasoning steps and reuses the production trip-generation solver plus lib/llm for day theming, and GET /api/home/poi-photo proxies Google Places photos for the static POI catalog in lib/home-survey.ts. Nothing is persisted.",
        ],
      },
      {
        id: "sad-trip-generator",
        title: "Trip generator pipeline",
        body: [
          "services/trip-generation/ is the shared backend for both the LINE /plan command and the web wizard at /app/trips/new. The two entry points feed the same survey state machine and the same generation pipeline; only the UX around them differs.",
          "Survey — Eight typed answers: destination, duration_days, party, party_size, budget_tier, vibe (multi-select), pace and free-text must_haves. The survey step order lives in services/trip-generation/survey.ts and is reused by both surfaces.",
          "Pipeline — A plain typed state machine (deliberately not LangGraph) drives: retrieve POIs → LLM pick assignment → solve route → on infeasibility, structured repair loop (≤ 2 retries) → persist. The LLM never sees opening hours or coordinates; it only emits which placeIds belong on which day. The solver enforces all logistics (open hours, travel time, day-length budget).",
          "Repair loop — When the solver reports an infeasibility (for example, 'Day 2 stop X opens at 10am, can't fit'), the LLM gets the structured report and swaps from the remaining shortlist. After two failed repair rounds the run terminates with GenerationFailedError(\"irreparable\").",
          "Output and fork — Generation always produces a private trip_template first. On the web, POST /api/app/trips/generate immediately forks the template into a real trip and returns the trip id, because the bento workspace is itself the preview. On LINE the same flow is two postbacks (generate → preview → fork) so the group can confirm before commit.",
          "Failure modes — GenerationFailedError carries a reason (gemini_unavailable, schema_invalid, persist_failed, invalid_answers, no_candidates, irreparable). Gemini calls are wrapped by the global circuit-breaker in lib/gemini.ts.",
        ],
        diagram: [
          "Survey answers (8 keys)",
          "        │",
          "        ▼",
          "  poi-engine.searchPoisByVibe → enrichWithLiveData",
          "        │              route-engine (shortlist of route compositions)",
          "        ▼",
          "  LLM: pick K placeIds per day  (no hours, no coords)",
          "        │",
          "        ▼",
          "  solver.solveItinerary  ─── feasible ──► persist → trip_template",
          "        │                                       │",
          "        │ infeasible (≤ 2 retries)              ▼",
          "        ▼                              fork (web: auto; LINE: postback)",
          "  structured repair report → LLM        ▼",
          "        │ swap from shortlist           trips row",
          "        └──────────────────►",
        ].join("\n"),
      },
      {
        id: "sad-data",
        title: "Data layer",
        body: [
          "All schema changes are timestamped Supabase migrations in supabase/migrations/. lib/database.types.ts is generated from these.",
          "Server code uses createAdminClient() from lib/db.ts (service role). Direct imports of the service-role key are forbidden.",
          "Row-level security is enabled with a default-deny posture (see migration 20260418000000_rls_no_anon_access). All cross-row access goes through the admin client on the server.",
        ],
      },
      {
        id: "sad-jobs",
        title: "Cron jobs",
        body: [
          "Schedules are declared in vercel.json. Each cron route lives under app/api/cron/ and authenticates via the CRON_SECRET header (lib/cron-auth.ts).",
          "Cron is the recovery and time-driven sweeper layer, not the primary delivery path. The list of active jobs is auto-generated above in the API reference section.",
        ],
      },
      {
        id: "sad-design-system",
        title: "Design system & motion",
        body: [
          "Design tokens live in app/globals.css as CSS variables (surfaces, text, borders, status, radius, shadows) mapped into Tailwind v4 via @theme inline. The web app uses a 'vibrant/expressive' language: a LINE-green brand anchor plus a secondary coral/cool/violet axis, gradient tokens (--gradient-brand/-warm/-cool/-aurora), glow shadows, and an animated ambient mesh behind the app shell.",
          "Fonts are loaded with next/font in app/layout.tsx: Space Grotesk (display), Inter (body), JetBrains Mono (numerics), exposed as CSS variables that --font-display/-text/-mono point at.",
          "Motion is centralized in components/motion/. MotionProvider wraps the /app shell with MotionConfig reducedMotion=\"user\"; variants.ts holds the shared fadeUp / stagger / springPop / pageTransition vocabulary; index.tsx exports reusable Reveal, Stagger/StaggerItem, PageTransition and AnimatedNumber helpers built on the 'motion' package (Framer Motion). CSS keyframes in globals.css cover the rest (skeleton shimmer, aurora pan, tile glow, bento cascade).",
          "Accessibility: every animation degrades under prefers-reduced-motion — the global CSS block collapses transitions to ~0ms and MotionConfig neutralizes transform/layout animations.",
        ],
      },
    ],
  },
};

const ZH_TW: DocsCopy = {
  pageTitle: "專案技術文件",
  pageSubtitle: "TravelSync 程式碼自動生成的參考文件：API、資料庫結構、使用指南與系統架構。",
  tocTitle: "本頁目錄",
  sections: {
    api: "API 參考",
    schema: "資料庫結構",
    guide: "使用指南",
    sad: "系統架構文件 (SAD)",
  },
  api: {
    intro:
      "下方列出 app/api/ 底下所有 HTTP 端點，依模組分組。內容於請求時掃描 app/api/**/route.ts 自動生成，永遠反映目前部署的版本。",
    methodHeading: "方法",
    pathHeading: "路徑",
    descHeading: "說明",
    sourceHeading: "原始碼",
    zodBadge: "zod",
    cronBadge: "cron",
    noDescription: "—",
  },
  schema: {
    intro:
      "資料表來自 supabase/migrations/*.sql。剖析器會合併原始 CREATE TABLE 與之後的 ALTER TABLE ADD COLUMN，因此欄位列表反映目前的 migration 狀態。",
    columnHeading: "欄位",
    typeHeading: "型別",
    modifiersHeading: "修飾子",
    createdIn: "建立於",
    columnCount: (n) => `${n} 個欄位`,
  },
  guide: {
    intro: "TravelSync 是一個 LINE 機器人，加上一個搭配的 Web App 用來規劃團體旅行。以下說明兩個介面如何協同運作。",
    sections: [
      {
        id: "guide-getting-started",
        title: "開始使用",
        body: [
          "把 TravelSync 機器人加入你的 LINE 群組。加入後在群組裡輸入 /start <目的地> <日期>（例如 /start Osaka Jul 15-20）即可建立一個新旅程。",
          "在本網站造訪 /app/sign-in 並以 LINE 登入。你的旅程會自動出現在工作區裡。",
        ],
      },
      {
        id: "guide-home-survey",
        title: "首頁互動式行程問卷",
        body: [
          "首頁本身就是一條互動式問卷流程。轉動地球並點選國家圖釘（目前提供日本、台灣與美國），接著從照片、影片與社群貼文牆中挑選吸引你的景點。",
          "送出選擇後，AI 代理會在畫面上即時規劃：把景點依地理位置分天、請 LLM 命名與排序每一天、用正式的路線求解器模擬時間，最後估算花費。",
          "完成的行程會呈現在動態地圖上，包含日期、抵達/離開時間，以及每站、每日與整趟旅程的預估花費。不需註冊帳號；此示範依訪客限流且不會儲存任何資料。",
        ],
      },
      {
        id: "guide-slash-commands",
        title: "LINE 斜線指令",
        body: [
          "/start — 建立新旅程，可附帶目的地與日期提示。",
          "/add — 加入行程項目（住宿、餐廳、活動、交通等）。",
          "/vote — 對含有多個選項的項目發起投票。",
          "/expense — 紀錄共同支出並與群組分帳。",
          "/itinerary — 將最新的行程回傳到群組。",
          "/help — 顯示所有支援的指令。",
        ],
      },
      {
        id: "guide-free-text",
        title: "群組中的自由訊息",
        body: [
          "任何非斜線指令的訊息都會被視為自由文字。群組監聽器會使用 Gemini 從中抽取日期、地點、航班、住宿、偏好與預算等資訊。",
          "抽取到的實體會自動合併到旅程中，群組可以用自然對話的方式持續討論，不需要學任何指令語法。",
        ],
      },
      {
        id: "guide-private-chat",
        title: "與機器人私訊",
        body: [
          "直接私訊機器人即可作為一對一的旅遊助理。私訊服務會走 orchestrator，可以回答問題、查詢航班與住宿，並把你所屬旅程的相關內容一併帶出。",
        ],
      },
      {
        id: "guide-web-app",
        title: "Web 工作區",
        body: [
          "旅程 — 一次瀏覽所有 LINE 群組正在規劃中的旅程。",
          "旅程工作區 — 主畫面是共用的群組聊天室：所有成員與 AI 規劃助手都在這裡對話。當你們聊天時，AI 規劃助手會閱讀對話，發現值得追蹤的事項（機票價格、天氣、飯店優惠、打包、照片）時，會直接在聊天中以卡片形式建議一個 bento 格子 — 點「新增格子」接受，或「暫時不要」忽略。你也可以把游標移到訊息上：若該訊息是某個代理人能處理的任務，會顯示一個 ⚡ 標記，將該訊息拖曳到右側欄的格子區即可自行建立對應的格子。",
          "右側欄 — 已確認的格子顯示在最上方，點開即可查看最新結果。成員與代理人對話在下方的「成員」區，而「旅程工具」連到總覽、行程、投票、支出、點子、地圖與打包頁面。",
          "地圖 — 跨旅程地圖，顯示曾被提及的所有地點。",
          "範本 — 公開的旅程範本，可一鍵 Fork 成新旅程。",
          "收件匣 — 通知：提醒、投票結果、事件處理與摘要。",
        ],
      },
      {
        id: "guide-voting",
        title: "投票與決策",
        body: [
          "每個旅程項目可以有多個選項（例如三間候選飯店）。任何成員都可以用 /vote 或在 Web App 中發起投票。",
          "達到多數決或截止時間時投票會自動關閉。平手會觸發一次延長，再無法決定就以系統規則收斂。",
        ],
      },
      {
        id: "guide-expenses",
        title: "支出與分帳",
        body: [
          "用 /expense 或 Web App 的支出頁面紀錄一筆共同支出。",
          "支援平均分攤、按份數、按金額三種分帳方式。Web App 會持續計算最少的轉帳次數，群組永遠知道誰該付誰多少。",
        ],
      },
      {
        id: "guide-privacy",
        title: "隱私與資料刪除",
        body: [
          "成員可以從工作區自行離開旅程。組織者可以從旅程卡片刪除旅程，這會永久移除行程、投票、文件與打包資料。",
          "若要刪除全部帳號資料，可在 /app/profile 使用刪除按鈕（會呼叫 POST /api/user/delete）。",
        ],
      },
    ],
  },
  sad: {
    intro:
      "TravelSync 所有非同步互動都會經過三個關鍵節點。本節記錄程式碼層面強制執行的不變條件，以及目前已實作的功能模組。",
    sections: [
      {
        id: "sad-overview",
        title: "系統概觀",
        body: [
          "TravelSync 是部署在 Vercel 上的 Next.js 16 App Router 應用，資料儲存在 Supabase Postgres。LINE Messaging API 是主要面對使用者的介面；/app/* 下的 Web App 提供更完整的 UI。",
          "所有來自 LINE 的訊息只會經過一個簽章驗證過的 webhook 端點；事件持久化在 line_events 資料表，再交由唯一的 dispatcher 處理；所有出站訊息都由唯一的 sender 發出。這個三節點設計是最重要的架構不變條件。",
        ],
        diagram: [
          "LINE → /api/line/webhook（驗章、Idempotent insert）",
          "          │",
          "          ▼",
          "    line_events（持久化 queue，每筆事件一列）",
          "          │  Fast path：Next.js after() 觸發 worker",
          "          ▼",
          "    services/event-processor（唯一 dispatcher）",
          "          │",
          "  ┌───────┼────────────────────┬──────────────────────┐",
          "  ▼       ▼                    ▼                      ▼",
          " 斜線指令 群組自由文字          私訊自由文字            Postback",
          " bot/    services/parsing    services/private-chat   handlePostback",
          "  │       │                    │                      │",
          "  └───────┴────────┬───────────┴──────────────────────┘",
          "                   ▼",
          "          lib/line.ts（唯一出站節點）",
          "                   ▼",
          "          outbound_messages（追蹤、重試、指數退避）",
        ].join("\n"),
      },
      {
        id: "sad-inbound",
        title: "入站：webhook + 持久化 queue",
        body: [
          "app/api/line/webhook/route.ts 驗證 LINE 簽章、以 line_event_uid 作為冪等鍵將事件寫入 line_events，並在一秒內回 200。",
          "處理用 Next.js 的 after() 排程為 happy path。/api/cron/process-events 是回收 sweeper，會撿回卡在 processing 超過 5 分鐘的列，以及 next_retry_at 已到的 failed 列。",
          "重試 backoff 為 2^(retry_count+1) 秒，上限 1 小時，由 services/event-processor 的 computeNextRetryAt 計算。",
        ],
      },
      {
        id: "sad-dispatcher",
        title: "Dispatcher 路由規則",
        body: [
          "services/event-processor 依 (event.type, source.type) 派發。私訊判斷：lineGroupId === userId。",
          "斜線指令（text.startsWith('/')）→ bot/router.ts，再進入 bot/commands/ 各自的 handler。",
          "群組自由文字 → services/parsing/（群組監聽器，由 Gemini 抽取實體）。",
          "私訊自由文字 → services/private-chat/（透過 orchestrator 進行 LLM 推理與工具呼叫）。",
          "Postback 不是指令，由 event-processor 的 handlePostback 以 'prefix|...' 形式的 data 解析。",
        ],
      },
      {
        id: "sad-outbound",
        title: "出站：唯一 sender + 追蹤",
        body: [
          "lib/line.ts 是 scripts/ 之外唯一引用 @line/bot-sdk 的檔案。每次 push 或 reply 都會寫入 outbound_messages，包含 retry_count 與 next_retry_at；失敗的訊息會由 cron sweeper 接手重送。",
          "通知是事件驅動：services/notifications/index.ts 提供 notifyXxx() 系列函式由業務碼呼叫。Cron 只處理提醒與摘要，永遠不是主要遞送路徑。",
        ],
      },
      {
        id: "sad-features",
        title: "已實作的功能模組",
        body: [
          "旅程與行程 — 旅程 CRUD、逐日行程、想法看板、含 Google Places 中繼資料的選項。",
          "旅程生成器 — 由 8 題問卷端到端生成完整行程，LINE /plan 指令與 /app/trips/new 精靈共用同一條管線。詳見下方專章。",
          "投票 — 帶截止時間的項目投票、平手延長機制、自動關閉（services/vote、/api/cron/vote-deadlines）。",
          "支出 — 共同支出，支援按份數／按金額／平均分帳，並持續計算最少轉帳次數。",
          "營運 — 追蹤清單、事件處理與後續追蹤、每日 briefing 與摘要、交通監控 cron。",
          "範本 — 可發佈的旅程範本，含 Like、留言、存取請求與授權。",
          "Orchestrator — 為私訊與 Web App 計畫管理用的 LLM agent，含工具呼叫上限。",
          "Agents — services/agents/ 底下的常駐型自動代理人。",
          "Web 工作區 — /app/* 頁面背後是 /api/app/* JSON 端點，支援 LINE Login 與 Email/Password 登入。旅程工作區是一個共用的群組聊天室（trip_chat_threads kind='group'）；發送訊息會喚醒該旅程的 orchestrator，它可透過 propose-only 的 grids.add_agent 動作建議一個 bento 格子。建議會以確認／忽略卡片的形式出現在聊天中，確認後即成為顯示在右側欄的 custom_grids。訊息也可以即時分類（POST /api/app/trips/[tripId]/chat/classify，以 LLM 比對代理人清單）；若對應到某個代理人，便可從聊天直接拖曳到右側欄格子區（原生 HTML5 拖放，MIME application/x-chat-task）以直接建立 custom_grid，若缺少必填設定則退回預先填好的新增格子對話框。",
          "首頁問卷示範 — 公開首頁是一條四階段問卷流程（地球 → 景點媒體牆 → AI 即時推理 → 動態行程地圖）。背後是兩個免登入、依 IP 限流的端點：POST /api/home/itinerary 以 SSE 串流推理步驟，重用正式的 trip-generation 求解器並透過 lib/llm 為每日命名；GET /api/home/poi-photo 為 lib/home-survey.ts 的靜態景點目錄代理 Google Places 照片。不儲存任何資料。",
        ],
      },
      {
        id: "sad-trip-generator",
        title: "旅程生成器 Pipeline",
        body: [
          "services/trip-generation/ 是 LINE /plan 指令與 Web 精靈 /app/trips/new 共用的後端。兩個入口走同一條問卷狀態機與同一條生成管線，只有外層 UX 不同。",
          "問卷 — 共 8 題類型化答案：destination、duration_days、party、party_size、budget_tier、vibe（複選）、pace 與自由文字 must_haves。題目順序定義於 services/trip-generation/survey.ts，兩個介面共用。",
          "Pipeline — 一個樸素的型別化狀態機（刻意不用 LangGraph）：retrieve POIs → LLM 指派 → solver 排線 → 若不可行則進入結構化 repair 迴圈（≤ 2 次重試）→ 持久化。LLM 看不到營業時間或座標，只輸出哪幾個 placeId 屬於哪一天；solver 負責所有物流（營業時間、移動時間、單日預算）。",
          "Repair 迴圈 — 當 solver 回報不可行（例如 'Day 2 X 點 10am 才開門，塞不下'），LLM 會拿到結構化報告並從候補清單中替換。連續兩次仍不可行時以 GenerationFailedError(\"irreparable\") 結束。",
          "輸出與 Fork — 生成永遠先產出一個 private trip_template。Web 端的 POST /api/app/trips/generate 會立即把 template fork 成正式 trip 並回傳 trip id，因為 bento 工作區本身就是預覽；LINE 端則拆成兩個 postback（generate → preview → fork），讓群組先確認再寫入。",
          "失敗類別 — GenerationFailedError 帶有 reason（gemini_unavailable、schema_invalid、persist_failed、invalid_answers、no_candidates、irreparable）。所有 Gemini 呼叫都包在 lib/gemini.ts 的全域 circuit-breaker 之中。",
        ],
        diagram: [
          "問卷答案 (8 個欄位)",
          "        │",
          "        ▼",
          "  poi-engine.searchPoisByVibe → enrichWithLiveData",
          "        │              route-engine（route 組合候補）",
          "        ▼",
          "  LLM：每日選 K 個 placeId（無時間、無座標）",
          "        │",
          "        ▼",
          "  solver.solveItinerary  ─── 可行 ──► 寫入 trip_template",
          "        │                                       │",
          "        │ 不可行（≤ 2 次重試）                  ▼",
          "        ▼                              Fork（Web：自動；LINE：postback）",
          "  結構化 repair report → LLM             ▼",
          "        │ 從候補清單替換                 trips 列",
          "        └──────────────────►",
        ].join("\n"),
      },
      {
        id: "sad-data",
        title: "資料層",
        body: [
          "所有 schema 變更都是 supabase/migrations/ 底下時間戳命名的 migration。lib/database.types.ts 從這些 migration 自動產生。",
          "Server 端使用 lib/db.ts 的 createAdminClient()（service role）。禁止直接引用 service-role key。",
          "Row-level security 預設拒絕（見 20260418000000_rls_no_anon_access）。所有跨列存取都在 server 上透過 admin client 進行。",
        ],
      },
      {
        id: "sad-jobs",
        title: "Cron 任務",
        body: [
          "排程在 vercel.json 中宣告。每個 cron route 位於 app/api/cron/ 底下，透過 CRON_SECRET header 驗證（lib/cron-auth.ts）。",
          "Cron 是回收與時間驅動的 sweeper 層，不是主要遞送路徑。目前啟用中的 cron 列表會自動出現在上方 API 參考章節。",
        ],
      },
      {
        id: "sad-design-system",
        title: "設計系統與動效",
        body: [
          "設計 token 以 CSS 變數定義於 app/globals.css（表面、文字、邊框、狀態、圓角、陰影），並透過 Tailwind v4 的 @theme inline 對應為工具類別。Web app 採用「鮮明／表現力」風格：以 LINE 綠為品牌主軸，輔以珊瑚／冷色／紫色次要色軸、漸層 token（--gradient-brand/-warm/-cool/-aurora）、光暈陰影，以及 app shell 背後的動態 ambient mesh。",
          "字型透過 app/layout.tsx 的 next/font 載入：Space Grotesk（標題）、Inter（內文）、JetBrains Mono（數字），以 CSS 變數提供，並由 --font-display/-text/-mono 指向。",
          "動效集中於 components/motion/。MotionProvider 以 MotionConfig reducedMotion=\"user\" 包覆 /app shell；variants.ts 收斂共用的 fadeUp / stagger / springPop / pageTransition 詞彙；index.tsx 匯出可重用的 Reveal、Stagger/StaggerItem、PageTransition 與 AnimatedNumber，皆建構於 'motion' 套件（Framer Motion）。其餘動效由 globals.css 的 CSS keyframes 提供（skeleton 微光、aurora 漸層流動、tile glow、bento 串接進場）。",
          "無障礙：所有動畫在 prefers-reduced-motion 下都會退化——全域 CSS 區塊將過場壓縮為約 0ms，MotionConfig 也會停用 transform/layout 動畫。",
        ],
      },
    ],
  },
};

export function getDocsCopy(locale: AppLocale): DocsCopy {
  return locale === "zh-TW" ? ZH_TW : EN;
}
